### PR TITLE
Map new concepts, refine mappings in Dellert

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
This PR:
- maps lists to the recently added concepts (see #1076)
- remapping the lists with the verbal meaning of 'quarrel' from QUARREL to QUARREL (VERB)
- maps some lists to ENCOUNTER (MEET) as proposed in #1077.
- refining some mappings in Dellert-2017-1016
- a few other arbitrary fixes

Since this PR incorporates some changes to Hale's list, I assume it might affect the respective Lexibank repository.

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
Since this PR involves some of the changes, proposed by @AnnikaTjuka, especially in regard to ENCOUNTER (MEET), it would be great if you could have a look at it!

**Comment by AnnikaTjuka** [comment]
Thank you, @Kristina-Pianykh, for making the changes! I'll have a look at it later today. @Schweikhard Would you also take a quick look since we discussed the issue on ENCOUNTER (MEET) together?

**Review by Schweikhard — APPROVED** [review]
That looks all very good.
Only thing I would bring up is: In Hale 1973, two entries are mapped to QUARREL (VERB). As one of them is specified to be quarreling with words, I suspect the other one might rather refer to some form of physical fighting.

**Review by AnnikaTjuka — APPROVED** [review]
Looks good!

**Comment by AnnikaTjuka** [comment]
Thanks, @Kristina-Pianykh! Feel free to merge.

**Pull request merged**
