### PR TITLE
Add Tjuka-2019 body parts

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [X] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR adds a small list of body part terms across 15 languages. The data is also available as a CLDF dataset [here](https://github.com/cldf-datasets/tjukabodyparts).

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@chrzyki Would you mind reviewing this PR?

**Comment by chrzyki** [comment]
Yep, I can have a look!

**Review by chrzyki — APPROVED** [review]
Looks all good, thanks! One small thing: I think we tend to mostly use empty cells to indicate `NA`s instead of directly putting `NA` (or similar) into the cell.

**Comment by AnnikaTjuka** [comment]
I forgot to mention this: I received an error message "missing translation" when the cells were empty. That's why I used "NA".

**Comment by chrzyki** [comment]
> 
> 
> I forgot to mention this: I received an error message "missing translation" when the cells were empty. That's why I used "NA".

Ahh, right! That was it - yeah, all good then! :)

**Comment by AnnikaTjuka** [comment]
Thanks for the review! I'll merge now.

**Pull request merged**
