### PR TITLE
Add modality norms for Chinese

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [X] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR adds the last list for issue #935.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@MacyL and @LinguList as our Chinese experts, would you mind reviewing the lists?

**Comment by AnnikaTjuka** [comment]
The PR includes two lists, the 171-item list includes single character words and the 61-item list includes two-morpheme compounds. The items are supposed to be only **adjectives**. I avoided double mappings, so please note if another item is more prototypical for a concept.

**Comment by LinguList** [comment]
Can I please have the output of the command that provides the statistics on the two concept lists? This would help me to what has been left over, etc. In this way, I can then more quickly check.

**Comment by AnnikaTjuka** [comment]
Oh yes, sure.
For Chen-2019-171:
```
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                   NUMBER  GLOSS
----------------  ---------  -----------------  --------  --------------------------
                          2  Chen-2019-171-1           1  pure white
                          3  Chen-2019-171-2           2  short
                          5  Chen-2019-171-4           4  concave
                          7  Chen-2019-171-6           6  spotty
                          9  Chen-2019-171-8           8  clumsy
                         11  Chen-2019-171-10         10  shrunken
                         12  Chen-2019-171-11         11  icy
                         13  Chen-2019-171-12         12  shiny
                         14  Chen-2019-171-13         13  vast/hazy/gray
                         17  Chen-2019-171-16         16  loud
                         18  Chen-2019-171-17         17  heavy
                         22  Chen-2019-171-21         21  of intense taste/ mellow
                         24  Chen-2019-171-23         23  crisp
                         27  Chen-2019-171-26         26  of mild taste
                         34  Chen-2019-171-33         33  powdery
                         35  Chen-2019-171-34         34  sweet
                         37  Chen-2019-171-36         36  bulged
                         40  Chen-2019-171-39         39  billowing
                         41  Chen-2019-171-40         40  chilling
                         42  Chen-2019-171-41         41  torrential
                         55  Chen-2019-171-54         54  stiff
                         56  Chen-2019-171-55         55  charred
                         57  Chen-2019-171-56         56  glistening white
                         61  Chen-2019-171-60         60  bright
                         64  Chen-2019-171-63         63  spicy hot
                         66  Chen-2019-171-65         65  tender
                         67  Chen-2019-171-66         66  bright/ loud
                         72  Chen-2019-171-71         71  sparse
                         73  Chen-2019-171-72         72  scorching
                         74  Chen-2019-171-73         73  clear (of water)
                         75  Chen-2019-171-74         74  jagged (of peaks)
                         76  Chen-2019-171-75         75  cold
                         78  Chen-2019-171-77         77  trembling
                         80  Chen-2019-171-79         79  boundless
                         81  Chen-2019-171-80         80  vast
                         82  Chen-2019-171-81         81  dense
                         83  Chen-2019-171-82         82  continuous
                         84  Chen-2019-171-83         83  misty
                         88  Chen-2019-171-87         87  withering
                         90  Chen-2019-171-89         89  intense taste/concentrated
                         93  Chen-2019-171-92         92  inclined to one side
                         95  Chen-2019-171-94         94  neat
                         98  Chen-2019-171-97         97  strong
                         99  Chen-2019-171-98         98  green
                        100  Chen-2019-171-99         99  limpid
                        102  Chen-2019-171-101       101  full
                        104  Chen-2019-171-103       103  harmonious
                        105  Chen-2019-171-104       104  soft
                        107  Chen-2019-171-106       106  sharp
                        108  Chen-2019-171-107       107  of urine's smell
                        109  Chen-2019-171-108       108  astringent
                        110  Chen-2019-171-109       109  dense
                        111  Chen-2019-171-110       110  of mutton's smell
                        112  Chen-2019-171-111       111  sparkling
                        116  Chen-2019-171-115       115  shaggy
                        117  Chen-2019-171-116       116  crisp/flaky
                        120  Chen-2019-171-119       119  scalding
                        121  Chen-2019-171-120       120  surging
                        122  Chen-2019-171-121       121  painful
                        124  Chen-2019-171-123       123  erect
                        126  Chen-2019-171-125       125  protruding
                        131  Chen-2019-171-130       130  tearful
                        132  Chen-2019-171-131       131  flourishing
                        133  Chen-2019-171-132       132  slight
                        134  Chen-2019-171-133       133  towering/ lofty
                        135  Chen-2019-171-134       134  lukewarm
                        136  Chen-2019-171-135       135  black
                        140  Chen-2019-171-139       139  slender
                        143  Chen-2019-171-142       142  whistling
                        145  Chen-2019-171-144       144  inclined
                        146  Chen-2019-171-145       145  spicy hot
                        147  Chen-2019-171-146       146  of fishy smell
                        149  Chen-2019-171-148       148  scorching
                        150  Chen-2019-171-149       149  vast/ magnificent
                        151  Chen-2019-171-150       150  copious
                        153  Chen-2019-171-152       152  be reluctant to part
                        154  Chen-2019-171-153       153  bright
                        155  Chen-2019-171-154       154  faint
                        156  Chen-2019-171-155       155  lucid
                        158  Chen-2019-171-157       157  luxuriant
                        160  Chen-2019-171-159       159  mixed
                        162  Chen-2019-171-161       161  dry
                        164  Chen-2019-171-163       163  swelling (in pain)
                        165  Chen-2019-171-164       164  orderly
                        166  Chen-2019-171-165       165  upright
                        170  Chen-2019-171-169       169  shining/ scorching
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
```

**Comment by AnnikaTjuka** [comment]
For Chen-2019-61:
```
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                 NUMBER  GLOSS
----------------  ---------  ---------------  --------  ----------------
                          3  Chen-2019-61-2          2  frosty
                          4  Chen-2019-61-3          3  frigid
                          5  Chen-2019-61-4          4  indifferent
                          6  Chen-2019-61-5          5  frigid
                          7  Chen-2019-61-6          6  grim
                          9  Chen-2019-61-8          8  stony
                         10  Chen-2019-61-9          9  massive
                         11  Chen-2019-61-10        10  rounded
                         12  Chen-2019-61-11        11  feminine
                         13  Chen-2019-61-12        12  insipid
                         16  Chen-2019-61-15        15  soft
                         17  Chen-2019-61-16        16  fine
                         18  Chen-2019-61-17        17  graceful
                         19  Chen-2019-61-18        18  soft and smooth
                         21  Chen-2019-61-20        20  bleak
                         22  Chen-2019-61-21        21  indifferent
                         23  Chen-2019-61-22        22  chilly
                         24  Chen-2019-61-23        23  insipid
                         25  Chen-2019-61-24        24  slightly sweet
                         26  Chen-2019-61-25        25  crisp
                         31  Chen-2019-61-30        30  strong
                         36  Chen-2019-61-35        35  scorching
                         37  Chen-2019-61-36        36  glorious
                         38  Chen-2019-61-37        37  pleasantly sweet
                         41  Chen-2019-61-40        40  brawny
                         43  Chen-2019-61-42        42  fine
                         44  Chen-2019-61-43        43  fine and smooth
                         45  Chen-2019-61-44        44  frail
                         46  Chen-2019-61-45        45  suffering
                         48  Chen-2019-61-47        47  vigorous
                         49  Chen-2019-61-48        48  bleak
                         50  Chen-2019-61-49        49  weak
                         51  Chen-2019-61-50        50  plump
                         53  Chen-2019-61-52        52  slight
                         54  Chen-2019-61-53        53  lightsome
                         55  Chen-2019-61-54        54  buoyant
                         56  Chen-2019-61-55        55  relaxing
                         57  Chen-2019-61-56        56  acerbic
                         58  Chen-2019-61-57        57  mellow
                         60  Chen-2019-61-59        59  astringent
                         61  Chen-2019-61-60        60  floppy
                         62  Chen-2019-61-61        61  fresh
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
```

**Review by LinguList — APPROVED** [review]
I think most of the cases are rather unproblematic. I was first wondering: why so many unlinked ones, but then saw that most of them are in fact linked beefore, and these are very specific rarely-used words, or words that have a very specific meaning. So I'd say this can be merged.

**Comment by AnnikaTjuka** [comment]
Thanks, @LinguList! Yes, I mapped very close to the links already established in Concepticon and left out the ambiguous cases. I'll merge now.

**Pull request merged**
