### PR TITLE
Epps2021

### PR DESCRIPTION
**Pull request by marthuis**
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                   NUMBER  GLOSS
----------------  ---------  -----------------  --------  ----------------------
                         31  Epps-2021-843-30         30  AUCTION
                         41  Epps-2021-843-40         40  BAKERY
                         97  Epps-2021-843-96         96  BOX ON THE EAR
                        129  Epps-2021-843-128       128  CATTLE FARMER
                        147  Epps-2021-843-146       146  CHURN-STAFF
                        195  Epps-2021-843-194       194  DEBRIS
                        224  Epps-2021-843-223       223  DRUNKENNESS
                        242  Epps-2021-843-241       241  EMAIL/POST
                        248  Epps-2021-843-247       247  EXCOMMUNICATION
                        406  Epps-2021-843-405       405  LATCH OR DOOR-BOLT
                        409  Epps-2021-843-408       408  LEADERSHIP
                        411  Epps-2021-843-410       410  LEARNING
                        435  Epps-2021-843-434       434  MAIN THING
                        508  Epps-2021-843-507       507  ONE'S OWN BUSINESS
                        576  Epps-2021-843-575       575  PRINTING
                        641  Epps-2021-843-640       640  SHAVINGS
                        711  Epps-2021-843-710       710  STUPIDITY
                        714  Epps-2021-843-713       713  SUMMER PASTURE (FÄBOD)
                        723  Epps-2021-843-722       722  TABLET (COMPUTER)
                        739  Epps-2021-843-738       738  TEXT MESSAGE
                        789  Epps-2021-843-788       788  VERSION
                        807  Epps-2021-843-806       806  WEB PAGE
                        831  Epps-2021-843-830       830  WOODWORK
1169                    513  Epps-2021-843-512       512  OX
1169                    704  Epps-2021-843-703       703  STEER
1220                    114  Epps-2021-843-113       113  BUTTOCKS/TAIL
1220                    724  Epps-2021-843-723       723  TAIL
1296                    698  Epps-2021-843-697       697  STAFF
1296                    797  Epps-2021-843-796       796  WALKING STICK
1300                    178  Epps-2021-843-177       177  COUNTRY
1300                    404  Epps-2021-843-403       403  LAND/ COUNTRY
1462                    566  Epps-2021-843-565       565  POT
1462                    790  Epps-2021-843-789       789  VESSEL
1488                    662  Epps-2021-843-661       661  SINK
1488                    726  Epps-2021-843-725       725  TAP/FAUCET
1747                    188  Epps-2021-843-187       187  CUSTOM
1747                    767  Epps-2021-843-766       766  TRADITION
1973                    201  Epps-2021-843-200       200  DEMON
1973                    203  Epps-2021-843-202       202  DEVIL (SMALL)
1979                    145  Epps-2021-843-144       144  CHISEL
1979                    630  Epps-2021-843-629       629  SCREWDRIVER/CHISEL
281                     217  Epps-2021-843-216       216  DOORPOST/POST
281                     563  Epps-2021-843-562       562  POST OR POLE
2984                    468  Epps-2021-843-467       467  MOUND
2984                    697  Epps-2021-843-696       696  STACK
388                     280  Epps-2021-843-279       279  FISHNET
388                     281  Epps-2021-843-280       280  FISHNET/NET
390                     531  Epps-2021-843-530       530  PENALTY OR PUNISHMENT
390                     580  Epps-2021-843-579       579  PUNISHMENT
480                     416  Epps-2021-843-415       415  LICENSE PLATE/PLATE
480                     555  Epps-2021-843-554       554  PLATE
770                     230  Epps-2021-843-229       229  EARRING/HANGER
770                     231  Epps-2021-843-230       230  EARRING/PLUG
779                     524  Epps-2021-843-523       523  PART
779                     562  Epps-2021-843-561       561  PORTION
874                     120  Epps-2021-843-119       119  CANDY/SWEETS
874                     719  Epps-2021-843-718       718  SWEET THING
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
Check: valid_concepticon_id
OK

@LinguList Hi Mattis! I've verified and formatted the list, reviewed all mappings, and added many new concepts in concepticon.tsv (3974-4014). Would you mind verifying their correctness and any other possible issue with this commit before I go ahead and map them to the other lists where they apply?

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@marthuis Have you checked to see if your proposed concepts appear in at least 2-3 other existing concept lists in Concepticon? I suspect that some of them are unique cases that are too idiosyncratic for our purposes, for example, EMAIL. See also @LinguList's comment here: https://github.com/concepticon/concepticon-data/issues/1129#issuecomment-1080846170

**Comment by marthuis** [comment]
@AnnikaTjuka Hi Annika, yes I have checked that beforehand, but I think it's best to discuss them here before proceeding to map in order to save time. Some concepts might be a little specific but they have good chances of appearing again in more lists!

**Comment by LinguList** [comment]
I would prefer to only add concpets that appear in at least one or two additional lists, and leave adding "potentially interesting concepts" later, as we have proceeded in this way so far.

**Comment by marthuis** [comment]
@LinguList Yes, all of these do appear in at least one other list!

**Comment by AnnikaTjuka** [comment]
@LinguList @marthuis To stay with my example, EMAIL seems to occur only in one other list ([Woll-2010-301-72](https://concepticon.clld.org/values/Woll-2010-301-72)), but as a VERB meaning. You are proposing the noun meaning. Maybe we could focus on a few frequently occurring cases for now and make a separate issue for potentially interesting concepts? Reviewing the concept list, as well as checking and mapping over 40 new concepts could become too complex in a single PR.

**Comment by LinguList** [comment]
Yes, I agree. We tend to be generally careful with adding new concepts, 
and we should stick to that here for now.

**Comment by AnnikaTjuka** [comment]
@marthuis and @LinguList: I briefly checked the proposed concepts and their occurrence in other lists. I would suggest adding the following:
- BEAUTY
- EXPERIENCE
- FREEDOM
- WISDOM

We could add the other concepts to an issue and discuss which ones we want to include at a later stage.

**Comment by LinguList** [comment]
Yes, this is a good plan, thanks, @AnnikaTjuka !

**Pull request closed without merging**
