### PR TITLE
Pallas 1786 and 1789 updates.

### PR DESCRIPTION
**Pull request by natalia-morozova**
closes issue #603

### CODE REVIEW

**Comment by LinguList** [comment]
Ah, we have an ugly change in the list ID now. That means, that you'll  have to do two things tto fix this:

1. change the conceptlists.tsv to modify the ID of the list Pallas-DATE-442 (instead of 441).
2. add a replacment statement to the "retired.json". 

The latter is in fact a bit annoying, but if you are good in regular expressions, you could do it yourself. If not, let us know and @chrzyki or me will look into this afterwards. In this case, open an issue that mentions that we need to work on retired.json and assign it to @chrzyki or myself or us both.

**Comment by natalia-morozova** [comment]
Got it, I would like to do it on my own (with @chrzyki 's assistance, of course).

**Comment by LinguList** [comment]
Good spirit!

**Comment by SimonGreenhill** [comment]
great work @natalia-morozova 🎉

**Pull request merged**
