### PR TITLE
Updated mappings and stats

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
I was wondering why some of the recently committed concepticon glosses weren't in my new mapping. I think this is because the mappings/map* files haven't been updated recently.

Therefore, I updated the mappings with `make_linkdata`. I also updated the stats with `stats`.

### CODE REVIEW

**Comment by LinguList** [comment]
this should be merged after the other three Prs have been merged. Please just merge them after approval.

**Comment by AnnikaTjuka** [comment]
Ok great! I will wait for one more approval for #711 from Carolin and #720 from Tiago and then I merge the PRs. Is the PR #703 with the small fixes from @Kristina-Pianykh ready to be merged?

**Comment by chrzyki** [comment]
#703 is done.

**Comment by AnnikaTjuka** [comment]
After PR #720 and #717 were merged into the master branch, I merged the changes into this branch and updated the mapping files as well as the stats.

**Pull request merged**
