### PR TITLE
Add body part relations

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [X] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

I added a bunch of Concepticon relations for body parts.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
The additions were already discussed with @Schweikhard and @LinguList via e-mail. So I'd ask them directly for their approval.

@LinguList I ran `concepticon test` and got the info `all integrity tests passed: OK`. I'll try to figure out why the checks failed.

**Review by LinguList — APPROVED** [review]

**Comment by LinguList** [comment]
Look, @Schweikhard, that's why I ask not to touch the relations, as we have not yet found time to fix the network structure in pyconcepticon. However, @AnnikaTjuka, this is easy to fix, and it should work perfectly if you change the order and paste the relations at the beginning of the text file, leaving all broader-narrower relations at the bottom.

**Comment by AnnikaTjuka** [comment]
Thanks, @LinguList! It worked.

**Review by Schweikhard — APPROVED** [review]
I see, thanks for explaining again.

**Pull request merged**
