### PR TITLE
Add Kaufman-1973-1028

### PR DESCRIPTION
**Pull request by Tarotis**
# Pull request checklist

- [x] add new concept list
- [x] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

Here comes the PR for adding the conceptlist by Kaufman, closing #170 . I will send the PDF to @chrzyki in a minute.

Can I ask you @AnnikaTjuka to review this PR?

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@Tarotis I'll try to review the PR this week but can't promise anything. Were all my comments in the Google Sheet clear or should I look out for specific changes that you didn't implement?

**Comment by Tarotis** [comment]
All comments were very clear and I followed them in all cases I think.

**Comment by AnnikaTjuka** [comment]
Ok, great! I'll check the PR as soon as possible.

**Review by AnnikaTjuka — APPROVED** [review]
Great work! Thanks to @Tarotis and @MuffinLinwist for the mapping. Everything looks good from my side. @LinguList Could you do a final check?

**Comment by AnnikaTjuka** [comment]
I just saw that there are conflicts with `conceptlists.tsv`, these should be fixed before merging.

**Comment by Tarotis** [comment]
The conflicts are resolved. I will wait for the final check from @AnnikaTjuka as requested by @LinguList before merging.

**Review by LinguList — APPROVED** [review]
All fine, I alrady approve, but I don't understand why one would quote this as a MISC. Can't you say it is an article appearing in the Journal "South American Archive of Endangered Languages" (or how it is called?):

Please also check here, with the original collection, which was digitized from about 2012 till 2018, so I would give it the date 2018, the reference, but the concept list has the date 1973, which is correct, since it was created back then. 

* https://www.ailla.utexas.org/islandora/object/ailla%3A124495

**Comment by LinguList** [comment]
I mean of course the Archive of the Indigenous Languages of Latin America.

**Comment by LinguList** [comment]
Why not say:

```bibtex
@incollection{Kaufmann1973,
  author = {Kaufman, Terrence},
  year = {2018},
  origyear = {1973},
  title = {Kaufman's basic concept list on historical principles}, 
  url = {https://www.ailla.utexas.org/islandora/object/ailla%3A246899},
  booktitle = {Latin American Languages Collection of Terrence Kaufman},
  publisher = {Archive of the Indigenous Languages of Latin America},
  address = {Austin},
  pages = {1-44},
}
```

**Comment by Tarotis** [comment]
I fixed the references according to your suggestion and also found another typo in the description, so I will merge this PR now.

**Pull request merged**
