### PR TITLE
Small fixes, new concept CUT OR HACK, unmap LIVE

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [X] add new Concepticon concept sets
- [X] add new Concepticon concept relations
- [X] refine existing Concepticon concept set mappings
- [X] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [X] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR solves #1051, #1061, #1052.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
The following changes were made: 
- Update of ontological categories 
- Fix typo and add a description 
- Unmap lists from 2309 LIVE 
- Introduce new concept incl. mappings for CUT OR HACK 

Thanks to @CarolinHu for pointing out the first two changes on existing concepts.

**Comment by AnnikaTjuka** [comment]
@chrzyki Would you moderate this PR?

**Review by chrzyki — APPROVED** [review]
Just had a look at the changes, thanks for taking care of that! Don't think another review is needed here so I'll just approve.

**Comment by AnnikaTjuka** [comment]
Thanks, @chrzyki! I'll merge.

**Pull request merged**
