### PR TITLE
Update datatype for Epps

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR adds a datatype specification to the Epps list.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@LinguList and @chrzyki Adding the "dontknow" cases for the ANIMACY column worked. One of the other columns could be rendered boolean - ABSTRACTNESS - but there is one blank and the following didn't work:
```
                    {
                      "titles": "ABSTRACTNESS",
                      "datatype": {
                        "base": "string",
                        "format": "1|0|"
                      }
                    },
```

**Comment by chrzyki** [comment]
> @LinguList and @chrzyki Adding the "dontknow" cases for the ANIMACY column worked. One of the other columns could be rendered boolean - ABSTRACTNESS - but there is one blank and the following didn't work:
> 
> ```
>                     {
>                       "titles": "ABSTRACTNESS",
>                       "datatype": {
>                         "base": "string",
>                         "format": "1|0|"
>                       }
>                     },
> ```

Does something like this work (can't test it right now, sorry, that is one space after `|`):

```json
{
    "titles": "ABSTRACTNESS",
    "datatype": {
        "base": "string",
        "format": "1|0| "
    }
},
```

Or (one space and `+` after `|`):

```json
{
    "titles": "ABSTRACTNESS",
    "datatype": {
        "base": "string",
        "format": "1|0| +"
    }
},
```

**Comment by AnnikaTjuka** [comment]
@chrzyki Both do not work, unfortunately. I'm guessing because there is no space in the cell but just blank space.

**Review by LinguList — APPROVED** [review]

**Comment by LinguList** [comment]
If there is one blank, could we actively replace it by an `x`, correcting the error here?

**Comment by AnnikaTjuka** [comment]
@LinguList If I add the "x" a different error occurs: `ERROR:Epps-2021-844: Duplicate name ot title in table schema: None`
Also, note that the line with the concept COMBINE is completely empty, which is probably an error.

**Comment by LinguList** [comment]
@AnnikaTjuka, I detected one problem in the list, so I'll quickly change this and also make sure the empty cells disappear!

**Comment by LinguList** [comment]
I'd make a new PR then. Sorry.

**Comment by AnnikaTjuka** [comment]
Ok, then I'll close this PR for now.

**Pull request closed without merging**
