### PR TITLE
adding three more lists

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Comment by xrotwang** [comment]
Do we have sources for these?

**Comment by xrotwang** [comment]
Btw. I'd find it more convenient if you would create PRs from branches **within** this repository, rather than from your fork. That way we could collaborate on the PRs, e.g. I just ran `concepticon stats` on this PR, but can't push the changes, because I don't have push access to your fork.

**Comment by LinguList** [comment]
All sources are in references.bib.

**Comment by LinguList** [comment]
As to the branching thing: I can do that, but I keep messing it up. If you have a good short-tutorial that illustrates this, I can use it in the future. But I suppose I'll add the stats now?

**Comment by LinguList** [comment]
Or do you mean the PDF or similar by sources?

**Comment by xrotwang** [comment]
Yes, PDFs was what I was thinking of.

**Comment by LinguList** [comment]
They are like 100 pages for two of them, I think we rather leave them out, as they also deliver the words in the languages. In the past, I would at times cut the real data out of the PDF, but it would take quite long to do this...

**Comment by LinguList** [comment]
Can we merge?

**Pull request merged**
