### PR TITLE
Corrected names for male/female animals

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
I indicated 2475 MALE GOAT as the alias of HE-GOAT (as discussed in [#730](https://github.com/concepticon/concepticon-data/issues/730)) and moved all the mappings from HE-GOAT to MALE GOAT.

I also changed the name of BOAR to BOAR (MALE PIG) (see [#466](https://github.com/concepticon/concepticon-data/issues/466)).

Besides, some of Chinese 野猪 instances were mapped to BOAR instead of WILD BOAR (namely, those in Chen-2012-888 and Sun-1991-1004). It would be nice if @MacyL could have a quick look at these mappings just to make sure they're correct now.

### CODE REVIEW

**Comment by chrzyki** [comment]
Hm, but we have to be careful with this, no? Not all boars are necessarily `male` if the concept is used to refer to the species: https://en.wikipedia.org/wiki/Wild_boar. Did you check for that?

**Comment by Kristina-Pianykh** [comment]
Yes, BOAR (MALE PIG) is different from WILD BOAR in that the former is a pig of male sex while the latter - a different species (and thus could be both male and female).

**Comment by chrzyki** [comment]
Good!

**Comment by Kristina-Pianykh** [comment]
I just renamed the concept BOAR that was already mapped in a number of lists. In most of the cases, they specify the concept by adding _male pig_ to it. In regard to Chinese, 公猪 is clearly a domestic pig in contrast to 野猪 (as far as I can judge by Google images :) ).

**Comment by Schweikhard** [comment]
The new concept name makes potential mismappings at least more obvious.

We might need some hyperonym over BOAR (MALE PIG) and WILD BOAR considering the ambiguity of the glosses, though.
Buck makes it clear in the book that he only means male pigs, and in most other cases it's contrasted with either sow or wild pig or both, but Hale and Lewis might both rather mean WILD BOAR from what I see there.

**Comment by Kristina-Pianykh** [comment]
@Schweikhard you're right, I see now. Both Lewis and Hale have only two pig-related concepts: _hog_ and _boar_. I just briefly checked that there could potentially be another dimension of distinction. As far as I can tell, 'hog' refers to a castrated male pig while 'boar' - to an uncastrated male pig. But then I need to refine the current definition of BOAR (MALE PIG) and add a new one (HOG).

**Comment by Schweikhard** [comment]
Oh, didn't notice/expect the hogs there.
There seems to be a UK/US difference.

Merriam Webster says it's "a domesticated swine especially when weighing more than 120 pounds (54 kilograms) " or "any of various animals related to the domesticated swine".

But Cambridge says:
"US: a pig, especially one that is allowed to grow large so that it can be eaten
UK: a male pig with its sexual organs removed, kept for its meat"

Which meaning can be expect Hale and Lewis to have meant? If they mean the US meaning, then hog might be PIG and boar is WILD BOAR. Otherwise, you're right and they make a new distinction.

**Comment by Kristina-Pianykh** [comment]
Currently, within one list (in both Lewis and Hale) 'hog' is mapped to PIG and 'boar' - to BOAR (MALE PIG), which doesn't make much sense as they don't form an opposition. Lewis is affiliated with a university in the US so I'll remap 'boar' in his list to WILD BOAR.

Which meaning is used in Hale, however, is hard to tell.

**Comment by Schweikhard** [comment]
Then I'd suggest to either treat Hale like Lewis, or to leave hog and boar in Hale unmapped.

**Comment by AnnikaTjuka** [comment]
I added @MacyL as a reviewer, see [description](https://github.com/concepticon/concepticon-data/pull/753#issue-378968887) :

| Besides, some of Chinese 野猪 instances were mapped to BOAR instead of WILD BOAR (namely, those in Chen-2012-888 and Sun-1991-1004). It would be nice if @MacyL could have a quick look at these mappings just to make sure they're correct now.

**Comment by chrzyki** [comment]
I'm fine with merging this, then @MacyL can prepare a clean PR.

**Comment by MacyL** [comment]
I will close my PR (Chinese) to the BOAR branch and then prepare another one.

**Comment by AnnikaTjuka** [comment]
I think there needs to be made one more commit concerning the Hale mapping.

**Comment by LinguList** [comment]
Can we merge this?

**Pull request merged**
