### PR TITLE
Added Dunn-2017-12

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
#365. I'm not quite sure about the list tag 'historical'.

I also corrected the links to the concept set [THIRSTY](https://concepticon.clld.org/parameters/847) in some lists where the concepts describe an action rather than a characteristic.

### CODE REVIEW

**Comment by chrzyki** [comment]
Yup, will take care of this! Thanks @Kristina-Pianykh!

**Comment by chrzyki** [comment]
@LinguList @Kristina-Pianykh This is now fixed with the release of `pyconcepticon 2.2.1`. I've re-triggered the Travis builds and everything is good to go.

**Comment by Kristina-Pianykh** [comment]
@chrzyki thank you! Could you also have a quick look at the changes I've proposed when you've got a chance?

**Comment by chrzyki** [comment]
Looks good to me. :)

**Comment by chrzyki** [comment]
Feel free to merge!

**Pull request merged**
