### PR TITLE
Adding of RED DEER as a sub-concept of DEER

### PR DESCRIPTION
**Pull request by MuffinLinwist**
- Addition of the subconcept on the list with all of the concepts
- Addition of relation btw DEER and RED DEER
- Mapping of the two ocurrences of the gloss on the list catalogue

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [x] add new Concepticon concept sets
  * [x] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [x] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [x] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR addresses the question raised in #1333 and tries to close issue #1335. It adds a new concept: RED DEER, as a sub-concept of the [1936 DEER](https://concepticon.clld.org/parameters/1936). I added the concept, the definition for it, the relation with DEER, and mapped the other two mentions of the gloss in our lists catalogue.
...

### CODE REVIEW

**Review by chrzyki — APPROVED** [review]
Looks good, thanks!

**Comment by MuffinLinwist** [comment]
> Looks good, thanks!

@chrzyki, thanks for the revision. I want to ask you what's the standard procedure now for this type of PR? Should I wait for one more revision in order to merge? Also, I have now another opened PR for a list which has this gloss ("red deer"). Should I wait until this is merge in order to map it?

**Comment by chrzyki** [comment]
AFAIK we don't do the normal 'big review' rounds for smaller changes like this, so in my opinion this should be all good. :)

Regarding workflow: The cleanest way imo would be to merge this PR, then update the branch of PR #1333 to get the updated Concepticon definition for `red deer`, then to update the list with the new mapping, and then to merge #1333. Please let me know if I can help!

**Comment by MuffinLinwist** [comment]
Thanks for answer my question :) I'll go ahead and do the workflow you proposed.

**Pull request merged**
