### PR TITLE
small fixes and links to new concepts

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
Just linked some concepts to the newly added concept sets (see #692) and fixed some minor issues (including #679 and #680).

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
I have only a small comment, concerning the following mapping:
- [ ] Mitterhofer-2013-300-294	293		take leave	1752	LEAVE

I understand "take (a) leave" more like "making holiday" and therefore, would not map it to LEAVE.

Everything else looks fine to me.

**Comment by LinguList** [comment]
Yes, I agree with @AnnikaTjuka

**Comment by Kristina-Pianykh** [comment]
Just fixed that, thank you for your comment @AnnikaTjuka!

**Comment by Schweikhard** [comment]
Some nice corrections, thanks!

I noted two mistakes:
The "(sb.)" in Buck does not mean "somebody" but "substantive", so it's the surprise and the honor.

And our MUSH (FOOD) is corn mush/polenta, isn't it?

**Comment by Kristina-Pianykh** [comment]
@Schweikhard you're right about Buck, I will then leave them unmapped. I was confused by a number of entries in his list marked with (sb.) which are linked to verbal concepts (e.g., dream (sb) is mapped to DREAM (SOMETHING), drop (sb.) - to DRIP (EMIT LIQUID), etc.). Should they be then also unlinked for the reasons of consistency?

Concerning MUSH (FOOD), while it does express that it's traditionally made out of corn, I meant it rather in more general terms. Do you think it doesn't fit here?

**Comment by Schweikhard** [comment]
Yes, there are some clear mismappings in Buck, now that I took a look.

The only thing currently linked to MUSH (FOOD) seems to be Snider, where it's "pap, mushy food", so I guess the definition just should be adjusted and this mapping here is correct.

**Comment by Kristina-Pianykh** [comment]
The last commits fix #708 and #709. Not sure if the concept relations (and the metadata) linked to older concept sets should be moved too (e.g., from FATHER'S SISTER to PATERNAL AUNT (FATHER'S SISTER).

**Comment by Schweikhard** [comment]
I think they should.

**Comment by LinguList** [comment]
We even need checks for this, but we don't have them by now, but having only the authoritative forms is vital for the concept relations.

**Comment by Kristina-Pianykh** [comment]
When I was adding the concept relations for PATERNAL AUNT (FATHER'S SISTER), I was following the example on Concepticon where each kinship term is linked via both "narrower" and "instanceof", which frankly I found a bit confusing. But now I see in your PR you mostly left the "narrower" link among kinship concepts. I will fix my mappings accordingly.

**Comment by Kristina-Pianykh** [comment]
@Schweikhard since the concept relations of the three kinship concepts are already modified in your PR, shall I duplicate your changes in my PR? Or just change those I added for the time being until your PR is merged?

**Comment by Schweikhard** [comment]
I merged my PR and resolved some conflicts that showed up here in that file.
So, you only need to remove those 2 duplicate relations and it should be fine.

**Comment by Kristina-Pianykh** [comment]
@Schweikhard thank you very much!

**Comment by Kristina-Pianykh** [comment]
@LinguList could you check if everything is alright and ready to be merged?

**Comment by LinguList** [comment]
@Kristina-Pianykh, I am sorry, but the conflicts must be resolved. You best do so from your side. We have a clash in new numbers now, can you check those please?

**Comment by chrzyki** [comment]
Will take care of this with @Kristina-Pianykh tomorrow and also will take the opportunity to walk her through the steps of updating the IDs.

**Comment by chrzyki** [comment]
Should be all good now I think. Will have another look at this in 30 minutes and then merge.

**Comment by chrzyki** [comment]
This also shows: Please be careful with tools like LibreOffice messing with what they think are number columns. At some point all the SRCIDs in Nagano were stripped of their leading `0`, resulting in rather unwieldy diffs. :)

**Comment by AnnikaTjuka** [comment]
Thanks for for fixing the fixes :-)
I'll edit my open PRs now.

**Pull request merged**
