### PR TITLE
Add Johansson-2020-11

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [x] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
#859. Tiny color list. I kept the RGB column the way it was in the source data but its datatype is declared as "string" now since all the three components are separated with commas within one column. I was wondering if one should split them into three to make it float.

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
@AnnikaTjuka would you be so kind to moderate the PR?

**Comment by AnnikaTjuka** [comment]
Regarding the separator, I suppose you can the following structure for the RGB column:
```
                    {
                        "name": "TYPICAL_ATTRIBUTE",
                        "separator": ", ",
                        "datatype": {"base": "string"}
                    },
```

**Comment by chrzyki** [comment]
Sure, happy to review!

**Review by chrzyki — APPROVED** [review]
Looks good so far to me and I agree with @AnnikaTjuka's proposal. Thanks for adding the list!

**Comment by Kristina-Pianykh** [comment]
Thanks for the tip with the separator!

**Review by AnnikaTjuka — APPROVED** [review]
I think as soon as the conflicts are resolved, this can be merged. Thanks for adding the list, @Kristina-Pianykh !

**Pull request merged**
