### PR TITLE
V3.0

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList @AnnikaTjuka I added a bit of documentation here and there about what has changed and how concepticon-cldf is going to become the main way to access concepticon data. So it may be worth reading through
https://github.com/concepticon/concepticon-data/pull/1274/files

**Review by LinguList — APPROVED** [review]
Thanks a lot, looks good to me! One short question: Do we also create the app data, or should I do that later? I'd then also make a new release with pysem...

**Comment by xrotwang** [comment]
Creating the JS app data isn't described in the release procedure and it isn't part of the release. So, I'd say you run `concepticon make_app` once the release is done.

**Comment by LinguList** [comment]
Alright!

**Review by AnnikaTjuka — APPROVED** [review]
Great!

**Pull request merged**
