### PR TITLE
Add Blomberg-2020-160 and change category of COURAGE and KINDNESS

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [X] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [X] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR adds a new data set and changes the ONTOLOGICAL_CATEGORY for two concepts (#1039 and #1031).

The list consists of **nouns** only!

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
<details><summary>Concepticon check</summary>
<p>
```
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                       NUMBER  GLOSS
----------------  ---------  ---------------------  --------  --------------
                         22  Blomberg-2020-160-21         21  jeans
                         24  Blomberg-2020-160-23         23  flask
                         32  Blomberg-2020-160-31         31  diamond
                         36  Blomberg-2020-160-35         35  kernel
                         41  Blomberg-2020-160-40         40  chess
                         46  Blomberg-2020-160-45         45  gadget
                         48  Blomberg-2020-160-47         47  furniture
                         49  Blomberg-2020-160-48         48  individual
                         51  Blomberg-2020-160-50         50  material
                         53  Blomberg-2020-160-52         52  pastry
                         56  Blomberg-2020-160-55         55  spice
                         57  Blomberg-2020-160-56         56  tool
                         62  Blomberg-2020-160-61         61  garment
                         63  Blomberg-2020-160-62         62  instrument
                         64  Blomberg-2020-160-63         63  container
                         65  Blomberg-2020-160-64         64  product
                         66  Blomberg-2020-160-65         65  vehicle
                         67  Blomberg-2020-160-66         66  device
                         69  Blomberg-2020-160-68         68  species
                         70  Blomberg-2020-160-69         69  art
                         71  Blomberg-2020-160-70         70  place
                         72  Blomberg-2020-160-71         71  jewelery
                         73  Blomberg-2020-160-72         72  package
                         74  Blomberg-2020-160-73         73  cookware
                         76  Blomberg-2020-160-75         75  content
                         77  Blomberg-2020-160-76         76  organism
                         79  Blomberg-2020-160-78         78  organ
                         80  Blomberg-2020-160-79         79  environment
                         84  Blomberg-2020-160-83         83  worry
                         88  Blomberg-2020-160-87         87  lust
                         89  Blomberg-2020-160-88         88  yearning
                         90  Blomberg-2020-160-89         89  humour
                         91  Blomberg-2020-160-90         90  horror
                         92  Blomberg-2020-160-91         91  comfort
                         96  Blomberg-2020-160-95         95  relief
                         97  Blomberg-2020-160-96         96  shock
                         98  Blomberg-2020-160-97         97  success
                         99  Blomberg-2020-160-98         98  hatred
                        100  Blomberg-2020-160-99         99  chrisis
                        101  Blomberg-2020-160-100       100  contempt
                        102  Blomberg-2020-160-101       101  love
                        103  Blomberg-2020-160-102       102  chaos
                        105  Blomberg-2020-160-104       104  excitement
                        106  Blomberg-2020-160-105       105  freedom
                        109  Blomberg-2020-160-108       108  pleasure
                        111  Blomberg-2020-160-110       110  friendship
                        113  Blomberg-2020-160-112       112  stress
                        114  Blomberg-2020-160-113       113  disappointment
                        115  Blomberg-2020-160-114       114  depression
                        116  Blomberg-2020-160-115       115  gratitude
                        117  Blomberg-2020-160-116       116  passion
                        118  Blomberg-2020-160-117       117  reward
                        122  Blomberg-2020-160-121       121  advice
                        125  Blomberg-2020-160-124       124  morale
                        128  Blomberg-2020-160-127       127  style
                        130  Blomberg-2020-160-129       129  prestige
                        131  Blomberg-2020-160-130       130  maturity
                        132  Blomberg-2020-160-131       131  variety
                        134  Blomberg-2020-160-133       133  wisdom
                        137  Blomberg-2020-160-136       136  position
                        138  Blomberg-2020-160-137       137  heritage
                        139  Blomberg-2020-160-138       138  fact
                        140  Blomberg-2020-160-139       139  term
                        141  Blomberg-2020-160-140       140  routine
                        142  Blomberg-2020-160-141       141  evidence
                        143  Blomberg-2020-160-142       142  phase
                        144  Blomberg-2020-160-143       143  tendency
                        146  Blomberg-2020-160-145       145  method
                        147  Blomberg-2020-160-146       146  lack
                        148  Blomberg-2020-160-147       147  fact
                        151  Blomberg-2020-160-150       150  pause
                        154  Blomberg-2020-160-153       153  ritual
                        155  Blomberg-2020-160-154       154  reaction
                        156  Blomberg-2020-160-155       155  attitude
                        157  Blomberg-2020-160-156       156  abundance
                        158  Blomberg-2020-160-157       157  theme
                        161  Blomberg-2020-160-160       160  loan
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
```
</p>
</details>

**Comment by AnnikaTjuka** [comment]
The lists included the concept COURAGE so I also changed the category as mentioned in #1039. 
@LinguList Would you moderate this PR?

**Review by LinguList — APPROVED** [review]
I think answer is verbal in concepticon? 

Otherwise, it seems okay to me, or do you think somebody else should another look at this, @AnnikaTjuka ?

**Comment by AnnikaTjuka** [comment]
Ah, yes, I somehow only have the noun meaning in my head when I see the word "answer". Will change it!

**Comment by AnnikaTjuka** [comment]
Since we don't have a native Swedish speaker in our group and the mappings were pretty straightforward, I guess we don't need another review.

**Pull request merged**
