### PR TITLE
Update tags for concept lists with ratings/norms/relations

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR updates the tags in some of the concept lists which were originally tagged as "ranked" for the lack of the new tags "ratings, norms, relations". This is based on the discussion in #823.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@LinguList Is it ok if you check and approve this PR? Or should I suggest a moderator?

**Comment by AnnikaTjuka** [comment]
@LinguList I mostly updated the tags for the norm datasets which I included at the beginning of this year and "acquisition" lists. I did not change the tags for all "ranked" lists! The changes involved the following lists:

ID | original tags | updated tags
-- | -- | --
List-2014-1280 | annotated | annotated, relations
Luniewska-2016-299 | acquisition | acquisition,ratings
Gampe-2017-48 | acquisition | acquisition,ratings
Auracher-2017-16 | acquisition | acquisition,ratings
Luniewska-2019-299 | acquisition | acquisition,ratings
Winter-2016-300 | ranked | ratings
Lynott-2013-400 | ranked | ratings
Lewis-2016-499 | ranked | ratings
Lynott-2009-423 | ranked | ratings
Izura-2005-499 | ranked | ratings, norms
Schroeder-2012-824 |  ranked | ratings
Xiao-2012-213 | ranked | ratings, norms
Desrochers-2010-330 | ranked | ratings
Monnier-2014-1031 | ranked | ratings
Verheyen-2019-1000 | ranked | ratings, relations
DiezAlamo-2018-750 | ranked | ratings
Maciejewski-2016-100 | ranked | ratings
List-2018-1105 | annotated | annotated, relations
Rzymski-2020-1624 | annotated | annotated, relations
Yao-2017-1100 | ranked | ratings

**Comment by AnnikaTjuka** [comment]
Should I add the tag "ranked" for the CLICS lists?

**Comment by LinguList** [comment]
At least [List-2014-1280](https://concepticon.clld.org/contributions/List-2014-1280) has the rank in the column: https://concepticon.clld.org/values/List-2014-1280-1

As a rule: if there's a RANK as a column, add "ranked" to the tags. That makes sense, right?

**Comment by LinguList** [comment]
Ah, here's a shell script example, how to find all lists that have a rank:

```
$ grep '\sRANK\s' conceptlists/*.tsv | awk '{print $1}' | sed s/conceptlists.// | sed s/:ID//
Dellert-2017-1016.tsv
Dyen-1964-154.tsv
Dyen-1964-196.tsv
Haspelmath-2009-1460.tsv
Kassian-2015-50.tsv
List-2014-1280.tsv
List-2018-1105.tsv
Nicholas-1989-60.tsv
Pagel-2007-200.tsv
Pozdniakov-2014-100a.tsv
Pozdniakov-2014-100b.tsv
Rzymski-2020-1624.tsv
Starostin-2007-110.tsv
Swadesh-1955-215.tsv
Tadmor-2009-100.tsv
Thomas-1960-168.tsv

```

**Comment by AnnikaTjuka** [comment]
Thanks! Then I'll only add the tag "ranked" to List-2014-1280, List-2018-1105, Rzymski-2020-1624, and additionally to Kassian-2015-50 (which has only the tag "basic" yet). 

The tags for the other lists were not changed and they already have the tag "ranked".

**Comment by LinguList** [comment]
Yes, that's nice, thanks for checking. And feel free to merge then!

**Pull request merged**
