### PR TITLE
Adding new concepts and mapping their appearances on past lists

### LINKED ISSUE #1377: New concepts COLLAPSE, HOARSE, and PLATEAU
As raised in the (already closed) #1372 PR, we can discuss the incorporation of new concepts `COLLAPSE`, `HOARSE`, and `PLATEAU`. We have already six lists with the first concept, four with the second, and four with the last one. I can propose a modification on a new PR if we decide on it, @LinguList, @AnnikaTjuka, and @chrzyki.

### PR DESCRIPTION
**Pull request by MuffinLinwist**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [x] add new Concepticon concept sets
  * [x] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

This PR is intended to close #1377, #1365, and #1327 by adding 9 new concepts (all of them with at least 3 occurrences in past concept lists).

### CODE REVIEW

**Review by chrzyki — CHANGES_REQUESTED** [review]
Looks all good to me, thank you very much. :) Small comment on the `SARDINE` definition and:

- [RonaTas-2011-431-158](https://concepticon.clld.org/values/RonaTas-2011-431-158) should probably be remapped to `LAWN`.

**Comment by chrzyki** [comment]
@MuffinLinwist I've implemented the comments. If you're happy I think we can merge.

**Comment by MuffinLinwist** [comment]
Thanks for the changes! Everything looks good from my side :)

**Comment by chrzyki** [comment]
Thank you for checking!

**Review by chrzyki — APPROVED** [review]

**Pull request merged**
