### PR TITLE
chaff/bran, calm of sea

### LINKED ISSUE #870: BRAN vs. CHAFF (HUSK) definitions
BRAN and CHAFF (HUSK) appear identical in their meanings as they are defined in the Concepticon. Compare:

|Concept|Concepticon definition|
|---|---|
|CHAFF (HUSK)|The outer shell or coating of a seed.|
|BRAN|The hard outer layers of cereal grain. It consists of the combined aleurone and pericarp.|

A closer look, however, reveals that 'bran' is the 'the broken **coat of the seed**' while 'chaff' - 'the inedible parts of a grain-producing **plant**, including husks and leaves'. The CHAFF is therefore more likely to be a hypernym for BRAN but the specification (HUSK) narrows the meaning down again to the outer covering of the seed.

You can see the confusion by the glosses mapped to these concepts. E.g., Chinese 糠 is mapped to both.

Or I may be overthinking and these concepts are simply duplicates and one of them should be retired.

### LINKED ISSUE #970: calm (of sea) in Key and other lists is wrongly linked.
We treat this as an adjective, but it seems, this is also a noun, so it is "the calm", that is, die Meeresstille.

### PR DESCRIPTION
**Pull request by Schweikhard**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [x] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [x] refine Concepticon concept definitions
- [ ] retire data

## Additional information
fixes #870
fixes #970

### CODE REVIEW

**Comment by Schweikhard** [comment]
Could you moderate this please @chrzyki ?

**Comment by chrzyki** [comment]
Sure and thanks for taking care of that, @Schweikhard. @LinguList, could you please review this?

**Review by CarolinHu — APPROVED** [review]
Don't mind me barging in here... Since these are rather straightforward and previously discussed/justified changes, I quickly reviewed so this can be merged soon.

**Comment by chrzyki** [comment]
Thanks @CarolinHu; I'll leave this one open until @LinguList did have time to look at it, since he originally proposed the `CALM (OF SEA)` concept.

**Review by LinguList — APPROVED** [review]

**Comment by Schweikhard** [comment]
Thanks for the reviews!

**Pull request merged**
