### PR TITLE
Map Smith-2015-97-55 and Dawson-1887-731-153 to POST

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

As discussed in #834 (then posted separately in issue #835), I mapped Smith-2015-97-55 and (after checking other 'post' glosses in the concepticon) Dawson-1887-731-153 to POST.

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
Could I ask you @Schweikhard to moderate this?

**Comment by Schweikhard** [comment]
With a very small change like this, I would assume that we need only one reviewer?
@MacyL do you want to review this?

**Comment by MacyL** [comment]
Judging by the description, I think both are correctly mapped :)

**Comment by Schweikhard** [comment]
I would agree on that, so I think this can be merged. (haven't ever moderated a PR here, anything else I need to do?)

**Comment by Kristina-Pianykh** [comment]
The PR moderator merges the PR then if they consider it ready. But I can do it too, I suppose :)

**Pull request merged**
