### PR TITLE
Retire concepts

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [X] refine existing Concepticon concept set mappings
- [X] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [X] retire data

## Additional information

This PR solves #927 and #924 .

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
For BELLY BUTTON  and NAVEL, I retired the former and remapped Izura-2005-499 to NAVEL.
For UPPER LEG and THIGH, I retired THIGH, renamed the concept gloss, and remapped the lists to the refined concept 471 UPPER LEG (THIGH).

Note that there is one list that uses both glosses: _thigh_ and _upper leg_ (Zgraggen-1980-380). I mapped both to  UPPER LEG (THIGH), but maybe only one should be mapped?

**Comment by AnnikaTjuka** [comment]
@Schweikhard Would you mind moderating this PR?

**Comment by LinguList** [comment]
Well, in fact, I did not know that there was a list that distinguishes the two, but this means in fact that we should not have merged the two concepts. The rule in concepticon is: if there is one concept list distinguishing two concepts, we accept the distinction. But on the other hand: it still seems to be synonymous. Can one of the lexibankers have a look at lexibank/zgraggenmadang and try to find out what is going on there? Are there really two different concepts in the list? @MacyL, could you do that?

**Comment by Schweikhard** [comment]
I can moderate - and based on the discussion started, I suggest @LinguList and @MacyL as reviewers.

**Comment by MacyL** [comment]
sure

**Review by LinguList — APPROVED** [review]
Okay, I think it is better to unlink Zgraggen "upper leg" and leave only "thigh". Otherwise okay.

**Comment by MacyL** [comment]
A quick check on zgraggenmadang repository. Although, the _upper leg_  is included in the conceptl-ist "Zgraggen-1980-380", it is not shown in the raw data, and it is not used by the repository, eitehr (checked the parameters.csv, the forms.csv, and the script). 
For some languages, there are two words for "leg", I wondered whether the authors were using upper leg to distinguish the two words.

**Comment by LinguList** [comment]
Okay, fine, this shows that the confusion is in the concept list itself ;)

**Comment by AnnikaTjuka** [comment]
Thanks for checking @MacyL ! I'll change the mapping according to @LinguList comment then.

**Comment by AnnikaTjuka** [comment]
I unmapped _upper leg_ in Zgraggen-1980-380. @Schweikhard would you mind taking a final look, so that I can merge the PR?

**Review by Schweikhard — APPROVED** [review]
Looks good to me!

**Comment by AnnikaTjuka** [comment]
Great! Thanks, everyone!

**Pull request merged**
