### PR TITLE
Add additional mappings

### PR DESCRIPTION
**Pull request by chrzyki**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

As discussed in #473.

### CODE REVIEW

**Comment by xrotwang** [comment]
Looks reasonable to me, but maybe should be reviewed by someone who was more active in adding the new concepts which can be mapped here.

**Comment by chrzyki** [comment]
Yes, I'll leave this open for a bit to make sure that no erroneous mappings that have been discussed previously are re-added (I've checked, but I might have missed something).

**Review by AnnikaTjuka — APPROVED** [review]
Looks good to me.

**Comment by chrzyki** [comment]
Thanks!

**Pull request merged**
