### PR TITLE
Small changes: FAN (ACTION), categories, and relation

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [X] refine existing Concepticon concept set mappings
- [X] refine Concepticon glosses
- [X] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR solves a few issues at once: #969, #966, #960, #947

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
Because these are all minor changes, I put them together in one PR:
- Change FAN ACTION to FAN (ACTION) and update mappings accordingly
- Update category and semantic field of MAKE A JOKE
- Update category of SQUEAK
- Fix relation between ENVY and FASTEN: The relation was between TIE and FASTEN, TIE had the wrong ID.

 @chrzyki Would you moderate this PR?

**Comment by chrzyki** [comment]
Sure, thanks for taking care of this @AnnikaTjuka. Would you mind me just reviewing?

**Comment by AnnikaTjuka** [comment]
> Sure, thanks for taking care of this @AnnikaTjuka. Would you mind me just reviewing?

I don't mind :) Thanks!

**Review by chrzyki — APPROVED** [review]
Looks all good! Thanks for taking care of these changes.

**Pull request merged**
