### PR TITLE
Luniewska fixes

### LINKED ISSUE #694: WILD ANIMAL = ZEBRA ? and SCARF = CLOTH ?
In the concept set WILD ANIMAL (958), the data from Luniewska-2016-299-158 and Luniewska-2019-299-158 are mapped to the word _zebra_. Although a zebra is a wild animal, should we use a new concept ZEBRA or delete the mapping?

### PR DESCRIPTION
**Pull request by chrzyki**
#694 feel free to add more fixes to this PR, thanks!

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
Luniewska-2016-299-74	74 --> iron = "Bügeleisen" our concept IRON refers to "Eisen"

**Comment by chrzyki** [comment]
Just push to the PR I think. Easier than the comments. :)

**Comment by AnnikaTjuka** [comment]
I didn't find anything else to fix.

**Comment by chrzyki** [comment]
Thanks! Closes #694.

**Pull request merged**
