### PR TITLE
Add Epps 2021

### PR DESCRIPTION
**Pull request by LinguList**
# Pull request checklist

- [x] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

@marthuis, I have taken the liberty of fixing this quickly, also since there were some problems with the modifications you made to the major concept list. so I closed the other issue.

### CODE REVIEW

**Comment by LinguList** [comment]
@AnnikaTjuka, could you have a look?

**Comment by LinguList** [comment]
I think we do not need to check all carefully, as this has been done many times now. Just basic check.

**Comment by LinguList** [comment]
```
CONCEPTICON_ID      LINE_NO  ID                   NUMBER  GLOSS
----------------  ---------  -----------------  --------  ----------------------
                         31  Epps-2021-844-30         30  AUCTION
                         37  Epps-2021-844-36         36  BACK OF HAND
                         41  Epps-2021-844-40         40  BAKERY
                         57  Epps-2021-844-56         56  BEAUTY
                         73  Epps-2021-844-72         72  BIRCH BARK
                         75  Epps-2021-844-74         74  BIRTH CERTIFICATE
                         97  Epps-2021-844-96         96  BOX ON THE EAR
                        129  Epps-2021-844-128       128  CATTLE FARMER
                        142  Epps-2021-844-141       141  CHILDHOOD
                        147  Epps-2021-844-146       146  CHURN-STAFF
                        162  Epps-2021-844-161       161  COD
                        168  Epps-2021-844-167       167  COMBINE
                        169  Epps-2021-844-168       168  HARVESTER
                        170  Epps-2021-844-169       169  COMPANY
                        178  Epps-2021-844-177       177  COUNTENANCE
                        190  Epps-2021-844-189       189  DAIRY
                        196  Epps-2021-844-195       195  DEBRIS
                        206  Epps-2021-844-205       205  DIFFERENCE
                        209  Epps-2021-844-208       208  DISAGREEMENT
                        210  Epps-2021-844-209       209  DISCUSSION
                        213  Epps-2021-844-212       212  DISTINCTION
                        225  Epps-2021-844-224       224  DRUNKENNESS
                        232  Epps-2021-844-231       231  EARRING/PLUG
                        242  Epps-2021-844-241       241  EMAIL
                        243  Epps-2021-844-242       242  EMAIL/POST
                        249  Epps-2021-844-248       248  EXCOMMUNICATION
                        250  Epps-2021-844-249       249  EXPERIENCE
                        301  Epps-2021-844-300       300  FREEDOM
                        333  Epps-2021-844-332       332  GRIP
                        344  Epps-2021-844-343       343  HAPPENING
                        375  Epps-2021-844-374       374  IMPRESSION
                        379  Epps-2021-844-378       378  INTERNET
                        410  Epps-2021-844-409       409  LEADERSHIP
                        412  Epps-2021-844-411       411  LEARNING
                        428  Epps-2021-844-427       427  LONELINESS
                        430  Epps-2021-844-429       429  LOTTERY
                        436  Epps-2021-844-435       435  MAIN THING
                        438  Epps-2021-844-437       437  MANAGEMENT
                        458  Epps-2021-844-457       457  MOBILE PHONE
                        469  Epps-2021-844-468       468  MOUND
                        486  Epps-2021-844-485       485  NEEDLE (PINE)
                        509  Epps-2021-844-508       508  ONE'S OWN BUSINESS
                        511  Epps-2021-844-510       510  OUTSKIRTS
                        526  Epps-2021-844-525       525  PASTRY
                        534  Epps-2021-844-533       533  PENSION
                        539  Epps-2021-844-538       538  PERSONALITY
                        563  Epps-2021-844-562       562  PORTION
                        571  Epps-2021-844-570       570  PRAISE/ BOASTING
                        577  Epps-2021-844-576       576  PRINTING
                        579  Epps-2021-844-578       578  PROPERTY
                        605  Epps-2021-844-604       604  ROD
                        611  Epps-2021-844-610       610  RUIN
                        626  Epps-2021-844-625       625  SCIENCE
                        629  Epps-2021-844-628       628  SCRAPER
                        636  Epps-2021-844-635       635  SEAT
                        637  Epps-2021-844-636       636  SECTION
                        642  Epps-2021-844-641       641  SHAVINGS
                        663  Epps-2021-844-662       662  SINK
                        698  Epps-2021-844-697       697  STACK
                        699  Epps-2021-844-698       698  STAFF
                        701  Epps-2021-844-700       700  STARCH
                        702  Epps-2021-844-701       701  STATION
                        705  Epps-2021-844-704       704  STEER
                        712  Epps-2021-844-711       711  STUPIDITY
                        715  Epps-2021-844-714       714  SUMMER PASTURE (FÄBOD)
                        720  Epps-2021-844-719       719  SWEET THING
                        724  Epps-2021-844-723       723  TABLET (COMPUTER)
                        740  Epps-2021-844-739       739  TEXT MESSAGE
                        767  Epps-2021-844-766       766  TRACTOR
                        777  Epps-2021-844-776       776  TUFT
                        783  Epps-2021-844-782       782  UNIT
                        790  Epps-2021-844-789       789  VALUABLE
                        799  Epps-2021-844-798       798  WEB PAGE
                        807  Epps-2021-844-806       806  VERSION
                        808  Epps-2021-844-807       807  VESSEL
                        822  Epps-2021-844-821       821  WISDOM
                        831  Epps-2021-844-830       830  WOODWORK
                        845  Epps-2021-844-844       844  YOUTH
1220                    114  Epps-2021-844-113       113  BUTTOCKS/TAIL
1220                    725  Epps-2021-844-724       724  TAIL
1300                    179  Epps-2021-844-178       178  COUNTRY
1300                    405  Epps-2021-844-404       404  LAND/ COUNTRY
1747                    189  Epps-2021-844-188       188  CUSTOM
1747                    768  Epps-2021-844-767       767  TRADITION
1979                    145  Epps-2021-844-144       144  CHISEL
1979                    631  Epps-2021-844-630       630  SCREWDRIVER/CHISEL
281                     218  Epps-2021-844-217       217  DOORPOST/POST
281                     564  Epps-2021-844-563       563  POST OR POLE
388                     281  Epps-2021-844-280       280  FISHNET
388                     282  Epps-2021-844-281       281  FISHNET/NET
390                     532  Epps-2021-844-531       531  PENALTY OR PUNISHMENT
390                     581  Epps-2021-844-580       580  PUNISHMENT
480                     417  Epps-2021-844-416       416  LICENSE PLATE/PLATE
480                     556  Epps-2021-844-555       555  PLATE
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
Check: valid_concepticon_id
OK

```

**Comment by marthuis** [comment]
@LinguList @AnnikaTjuka hank you for all the modifications. I can take care of the concept refinements, relations and mappings for other lists after you merge this corrected version of Epps2021 with the final decisions for the new added concepts. Would that be helpful?

**Comment by LinguList** [comment]
@marthuis, I suggest to ignore the new concepts for now.  In the future, we need to be more careful and discuss new concepts to be added in an issue before. So we decided now to ignore the newly added concepts and instead link the data without them, as you can see in the PR I made.

**Pull request merged**
