### PR TITLE
Add Capell 1956 wordlist

### PR DESCRIPTION
**Pull request by lannin**
# Pull request checklist

- [x] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

### CODE REVIEW

**Comment by lannin** [comment]
The source of the wordlist is https://indigenous.sl.nsw.gov.au/collection-items/vocabulary-600-words-forty-north-australian-languages-1956-arthur-capell

**Comment by LinguList** [comment]
Thanks, @lannin! We would need a couple of more details, but you can provide them here, and we help you to run through the review process. First, can you provide the source, ideally in BibTex, but you can also for now paste it here in the comment fields.

**Comment by LinguList** [comment]
Then, if you have, provide a link to the PDF where we can find the concept list.

**Comment by LinguList** [comment]
@AnnikaTjuka, I will coordinate this PR.

**Comment by lannin** [comment]
{ author       = {Arthur Capell},
  howpublished = {Ms.},
  pages        = {146},
  title        = {A vocabulary of 600 words in forty North Australian languages},
  year         = {1956},
  hhtype       = {wordlist},
  inlg         = {English [eng]},
  lgcode       = {1 Iwaidja = Iwaidja [ibd], 2 Gunwinggu = Bininj Kun-Wok [gup], 3 Kakadu = Gagadu [gbu], 4 Amarag = Amurdak [amg], 5 Mangeri = Mangerr [zme], 6 Gunavidji = Djeebbana [djj], 7 Burera = Burarra [bvr], 8 Rainbarngo = Rembarunga [rmb], 9 Groote Eylandt = Anindilyakwa [aoi], 10 Nunggubuyu = Wubuy [nuy], 11 Gobabingo = Gupapuyngu [guf], 12 Ridarngo = Ritarungo [rit], 13 Wang'uri = Dhangu [dhg], 14 Djinba = Djinba [djb], 15 Jandjinang = Djinang [dji], 16 Jarnango = Yan-nhangu [jay], 17 Galbu = Djangu [dhg], 18 Warameri = Djangu [dhg], 19 Gomaij = Gumatj [gnn], 20 Manggalili = Gupapuyngu [guf], 21 Mararba = Gupapuyngu [guf], 22 Djabu = Dhuwal [duj], 23 Riraidjango = Djangu [dhg], 24 Dalwongo = Dayi [dax], 25 Mara = Mara [mec], 26 Anjula = Yanyuwa [jao], 27 Alawa = Alawa [alh], 28 Mangarai = Mangarayi [mpc], 29 Ngandi = Ngandi [nid], 30 Wandarang = Wandarang [wnd], 31 Buan = Ngalkbun [ngk], 32 Ngalakan = Ngalakan [nig], 33 Djauan = Jawoyn [djn], 34 Jangman = Yangman [jng], 35 Uningang = Urningangg [urc], 36 Gorogone = Guragone [gge], 37 Gundangbon = Ngalkbun [ngk], 38 Maung = Maung [mph], 39 Gunbalang = Kunbarlang [wlg], 40 Margu = Margu [mhg]},
  macro_area   = {Australia}}
The source of the wordlist is https://indigenous.sl.nsw.gov.au/collection-items/vocabulary-600-words-forty-north-australian-languages-1956-arthur-capell , but it is not pdf .

**Comment by lannin** [comment]
Also below is a list of words that have not been assigned concepts but are on existing lists:
also
bachelor
bale out
barramundi
capsize
consider
curlew
drone-pipe
dugong
firestick
green ant
jabiru
lizard-frilled
murderer
native plum
paperbark
pearlshell
pierced nasal septum
plenty
plover
pouch (‘roo)
seaweed
bloodwood tree
ironwood tree
wattle
stringybark
waterhole

**Comment by LinguList** [comment]
Thanks, we'll have our research assistants add the information, so we can add this to Concepticon. @MuffinLinwist, could you take a first look at this list, and please, do the following:

1. add it to a google doc (I'll share the link with @lannin later directly)
2. add page numbers for all concepts, so we can link them
3. add the concepts that are not linked so far (mentioned in the thread)
4. make the bibtex entry
5. make the JSON file

Please make a new PR for this, so we can then update, and also show @lannin, which information we require in PRs in addition to the TSV file.

When merged, we need to update CONTRIBUTORS information for @lannin.

**Comment by MuffinLinwist** [comment]
I already address this in #1315. So, I'll close this one, @LinguList and @lannin.

**Pull request closed without merging**
