### PR TITLE
Add FEMALE (OF ANIMAL)

### PR DESCRIPTION
**Pull request by SimonGreenhill**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [X] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This item should be mapped to FEMALE (OF ANIMAL)

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
Also found in Oskolskaya2021 list (https://github.com/concepticon/concepticon-data/pull/1149), so I think we need a new concept defined?

**Comment by chrzyki** [comment]
> Also found in Oskolskaya2021 list (#1149), so I think we need a new concept defined?

Sounds good, particularly because we now have more instances where the new concept can be applied.

**Comment by LinguList** [comment]
So this would then be added along with the Oskolskaya list?

**Comment by SimonGreenhill** [comment]
ok, I'll add a new concept in PR1149

**Comment by SimonGreenhill** [comment]
closing in favor of #1149

**Pull request closed without merging**
