### PR TITLE
Small fixes and mapping of left-over concepts to new concept sets

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [x] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [x] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [x] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
This PR:
- solves #1066;
- maps the left-over concepts to the new concept sets added in #1072;
- splits TAME into TAME (property) and TAMING (action) and maps tame-verbs to TAMING;
- maps a few more left-over concepts to BE DEFEATED and SATIATED.

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
@Schweikhard, could I ask you to moderate/review this PR?

**Comment by Schweikhard** [comment]
@AnnikaTjuka @LinguList do you want to review?

**Review by LinguList — APPROVED** [review]
Thanks!

**Review by AnnikaTjuka — APPROVED** [review]
Looks good!

**Pull request merged**
