### PR TITLE
Added two new concepts (piano (instrument), top (toy))

### PR DESCRIPTION
**Pull request by alzkuc**
two new concepts: PIANO (INSTRUMENT) and TOP (TOY) 

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [X] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

### CODE REVIEW

**Comment by LinguList** [comment]
@alzkuc, can you elaborate why you suggest to add these? Are they already often used? Are they useful for many lists that you intend to map, etc?

**Comment by LinguList** [comment]
We'd then discuss if it is worth adding the new concepts here.

**Comment by alzkuc** [comment]
Hallo @LinguList! Ja genau, danke für die schnelle Reaktion. Diese zwei Konzepte kommen in sehr vielen Listen vor, deshalb wollte ich sie hinzufügen, wenn du damit einverstanden bist. :-)

**Comment by LinguList** [comment]
Are they also in existing lists? This makes their integration easier. Could you share, since we will discuss this with other editors, like @AnnikaTjuka and @FredericBlum, some arguments and some summary on the concept definitions?

**Comment by alzkuc** [comment]
> Are they also in existing lists? This makes their integration easier. Could you share, since we will discuss this with other editors, like @AnnikaTjuka and @FredericBlum, some arguments and some summary on the concept definitions?

Hi @AnnikaTjuka and @FredericBlum: whenever you have time, would you please be so kind and let me know your thoughts? I would like to add two new concepts to concepticon.tsv. Thanks a lot in advance! :-) 

Here's a summary:

PIANO (INSTRUMENT): A large musical instrument with a row of black and white keys that are pressed to play notes.
TOP (TOY): A toy with rounded sides, a flat top and a point at the bottom that turns round and round on the point.

Sure! I think it would be useful to add these two new concepts—PIANO (INSTRUMENT) and TOP (TOY)—to the concepticon.tsv, as they appear in many of the lists I have recently mapped. I did a simple search for the word _piano_ in all the lists, and it comes up in 10 of the existing ones as well as 13 of my own, totaling 23. The word top (toy) appears in 11 of my lists, indicating that it is a common object to include in picture-naming tasks. Additionally, the top is not a modern world item, it is considered one of the oldest toys in the world, therefore more likely to appear in other (of my) wordlists as well.

**Comment by AnnikaTjuka** [comment]
@LinguList @alzkuc The concept PIANO also exists in other lists, but we have not added it yet because it is not necessarily relevant for the language comparison, since most languages use the original word ‘piano’. I could not find the concept TOP (TOY) in other lists. I would therefore only add PIANO and not TOP (TOY). 

@alzkuc A more general note: It would be great if we could initially discuss adding new concepts in an issue so that we can decide on possible mappings. The PR should be the last step and would include mappings to all existing Concepticon lists.

**Comment by alzkuc** [comment]
> @LinguList @alzkuc The concept PIANO also exists in other lists, but we have not added it yet because it is not necessarily relevant for the language comparison, since most languages use the original word ‘piano’. I could not find the concept TOP (TOY) in other lists. I would therefore only add PIANO and not TOP (TOY).
> 
> @alzkuc A more general note: It would be great if we could initially discuss adding new concepts in an issue so that we can decide on possible mappings. The PR should be the last step and would include mappings to all existing Concepticon lists.

Alright, thanks for your reply! @AnnikaTjuka Next time, I will create an issue with these first. Thank you for the note on which word is usually used for the concept. “Top,” when it appears, is typically expressed by a unique word in most languages rather than a borrowing. This is another reason I thought it might be useful to add it.

**Comment by AnnikaTjuka** [comment]
I'm closing this PR for now.

**Pull request closed without merging**
