### PR TITLE
Add Nordenskioeld-1905-50 concept list

### PR DESCRIPTION
**Pull request by Tarotis**
# Pull request checklist

- [x] add new concept list
- [x] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR adds the Nordenskioeld-1905-50 concept list. Some notes on decisions that could be problematic:

- I changed all `ö` to `oe`
- The  terms "Pauchi-Huhn" (Pauchi-chicken) was mapped to `CHICKEN`, and the term `Stearin-Licht` (stearin light/candle) to `CANDLE`. Both are sub-forms of the more general and already added concept. For the chicken, I couldn't find any additional information regarding the species, while the candle seems very appropriate
- How do I find out if copyright is existing? Does an openly available PDF in the web mean I can just send it to you, following the proposed workflow?

### CODE REVIEW

**Comment by LinguList** [comment]
That was fast, @tarotis. We have @mathildavz new on board to learn and help with concepticon. So @mathildavz, I'll later ask you to review this submission, would that be okay with you?

**Comment by mathildavz** [comment]
Of course!

**Comment by mathildavz** [comment]
Of course, @LinguList

**Comment by LinguList** [comment]
Furthermore, you can subscribe to individual repositories there, so you either get news or not.

**Comment by mathildavz** [comment]
Sounds great! Thanks! @LinguList

**Comment by LinguList** [comment]
I will be a bit slow, but I will try to inform about all major points of criticism by the end of the day. So you can then have a look at your convenience later, @mathildavz

**Comment by LinguList** [comment]
Okay, @mathildavz , first pass. @Tarotis writes they add a new concept list (which is correct) and new metadata. The latter is not entirely correct. Our files consist of a TSV document and a metadata.json file (see files listed here: https://github.com/concepticon/concepticon-data/pull/1181/files), but the metadata file for the TSV is not really metadata, it is a list of basic instructions of how to interpret what we find in the TSV file.

**Comment by LinguList** [comment]
If you check the [file list](https://github.com/concepticon/concepticon-data/pull/1181/files), which lists all files that have been changed by @tarotis, you can see that there are as many as four files with changes. I list them with their *relative paths*:

* [concepticondata/conceptlists.tsv](https://github.com/concepticon/concepticon-data/pull/1181/files#diff-32eaf01e5c762e127a5064e104969c3d271291873c198621134902f072eecf50)
* [concepticondata/conceptlists/Nordenskioeld-1905-50](https://github.com/concepticon/concepticon-data/pull/1181/files#diff-93c21dacfe0b865f12d7873e98fe346fe3c261c10e9061a4791300eaf121bccf)
* [concepticondata/conceptlists/Nordenskioeld-1905-50-metadata.json](https://github.com/concepticon/concepticon-data/pull/1181/files#diff-21ed76715938d6df89b9012a91c7e952ff9a5f0f231f50be2bd086f8c2c7147b)
* [concepticondata/references/references.bib](https://github.com/concepticon/concepticon-data/pull/1181/files#diff-e9f343f2093978463b2c12bd4721fa339698ba827890f4b841d4a37e83545a65)
*

**Comment by LinguList** [comment]
Two files were already there (references.bib and conceptlists.tsv), so @tarotis just added some content, and you can see that using the DIFF (for "differences") view, which colors original and modified text, like you know from plagiarism detection of dissertations by politicians.

**Comment by LinguList** [comment]
The two new files are a TSV file (Nordenskioeld-1905-50.tsv) and a metadata.json file (Nordenskioeld-1905-50.tsv-metadata.json). The conventions for the file namings are:

The concept list is identified by the author name Nordenskioeld, the year 1905 and the number of items 50. Then, we add the ending TSV and later metadata.json. [JSON](https://en.wikipedia.org/wiki/JSON) is a very straightforward file format that resembles Python dictionaries. And TSV is of course Tab-Separated-Values. So we have a simple table.

**Comment by LinguList** [comment]
To fill in the metadata file, one does not need to be too scared. There are just enough that one can use as a template and then fill in the names of the individual columns, as one can see in the examples. We can provide more explanation if needed.

**Comment by LinguList** [comment]
The file `conceptlists.tsv` was extended by one line that presents the new concept list. 

@tarotis has written (following the basic header, in one line) the following content:

Field | Content | Note 
--- | --- | --- 
ID | Nordenskioeld-1905-50 | Identifier
Author | Nordenskiöld, Erland | author's name
Year | 1905 | year of publication
List_Suffix |  | this may be a and b if the ID is not unique as there are two lists in the same year by the same author
Items | 50 | number of concepts
Tags | basic, areal | information on the classification, we have fixed items here 
Source_Language | German | langauge in which the list is written
Target_Language | South American languages | language for whose investigation the list is intended
URL | https://www.pueblos-originarios.ucb.edu.bo/Record/106001946?lng=da  | URL to the link
Refs | Nordenskioeld2005 | reference to the BIB-Tex file `references.bib`
Note | This list compares five languages of the Madre de Dios region in the Peruvian selva across 50 basic concepts. While four languages are part of the hypothesized Pano-Takana language family, one language is part of the Harákmbut family. Of the Pano-Takana languages, two are unclassified with respect to the internal classification of the family. The data is based on fieldwork from the original author which was done in 1904 and 1905. | Text introducing the list.
Pages | 265-312 | page rank on which teh list can be found

**Comment by LinguList** [comment]
I will now start reviewing this part by writing comments inline.

**Comment by LinguList** [comment]
In order to check this, I first test the URL and have a look at the original document.

**Comment by LinguList** [comment]
So, @Tarotis, this also means, you should add the name of the PDF file to the field `PDF`.

**Comment by LinguList** [comment]
Here are a couple of things that need to be changed.

First the bibtex key is Nordenskiold2005, but we have the original scan, so there is no reason to give it a key referencing the year to 2005, if we have the original, even if the scan is from 2005. It is like a reprint, in some sense, but one does not need to mention this.

**Comment by LinguList** [comment]
So the key should be Nordenskiold1905:

```
@Article{Nordenskioeld2005,
  Author                              = {Nordenskiöld, Erland},
  Pages                               = {265--312},
  Volume                              = {25},
  Address                             = {Stockholm},
  Journal                             = {Ymer},
  Name                                = {Beiträge zur Kenntnis einiger Indianerstämme des Rio Made de Dios-gebietes},
  Year                                = {1905},
}
```

**Comment by LinguList** [comment]
Next problem: the line:

```
Name = {Beiträge zur Kenntnis einiger Indianerstämme des Rio Made de Dios-gebietes},
```

should be rather:

```
Title = {Beiträge zur Kenntnis einiger Indianerstämme des Rio Made de Dios-gebietes},
```

And  since it is German, we usually add a translation in `[]` brackets after the entry in the title.

```
Title = {Beiträge zur Kenntnis einiger Indianerstämme des Rio Made de Dios-gebietes [Contributions to the Knowledge about some Indian tribes of the area of the Rio Made de Dios]},
```

Please correct my translation, if you have better ideas.

**Comment by LinguList** [comment]
Next problem: it is an article, but we have the filed `Address` in it. For an Article, we do not need the Address. The journal [Ymer](https://en.wikipedia.org/wiki/Ymer_(journal)) is an old Swedish journal published in Stockholm, but since we know this by the fact that it is a journal with a fixed name, no need to add it.

**Comment by LinguList** [comment]
Last point: journals have volumes (25 points to the 25th year of the journal's publication) and also issues. If you read the first page, you can see that there is `H.3` on it, so this points to issue (=Heft) 3. So please add `number = {3}` (issue is "number" in Bibtex).

**Comment by LinguList** [comment]
@mathildavz, if you check the TSV file now, you can see that @Tarotis has the columns 

Column | Explanation
--- | ---
ID | Identifier, combination of the concept list identifier and a number (consecutiv)
Number | An extra numerical field, which is typically showing the numbering we find in the data.
Gloss | This is identiocal with the field English, but we use it if there is no original English translation, but we added it, so Gloss means: this was translated by Concepticon people
Concepticon ID | the identifier to the concepticon, if it can be found, a way to link manually is also at [https://digling.org/calc/concepticon/](https://digling.org/calc/concepticon/)
Concepticon Gloss | the gloss of the concepticon
German | A field that @tarotis added in order to show the original German entry in the concept list

So the first lines look like:

ID	| NUMBER	| GLOSS	| CONCEPTICON_ID	|  CONCEPTICON_GLOSS	| GERMAN
--- | --- | --- | --- | --- | ---
Nordenskioeld-1905-50-1	| 1	| ear	| 1247	| EAR	| Ohr
Nordenskioeld-1905-50-2	| 2	| eye	| 1248	| EYE	| Auge

**Comment by LinguList** [comment]
Our task is now to check all 50 concepts and see if the links are correct and the translations are correct.

**Comment by LinguList** [comment]
37 shirt and 38 headband are too loosely translated, I think. I'd not link them to concepticon and make the translation more literal.

**Comment by LinguList** [comment]
43 Stearinlicht is also too freely linked, so again, remove concepticon link.

**Comment by LinguList** [comment]
These would be my comments for now.

**Comment by Tarotis** [comment]
The main reason I did not chose `STONE` was its specific description for construction: `...that is used in construction, either crushed for use as aggregate or cut into shaped blocks as dimension stone.' It did not seem appropriate to me.

With respect to the soon-to-be-unlinked concepts: Should I create new entries, or link them as `<NA>`?

**Comment by LinguList** [comment]
Where did you read that about the "Stein"? The concept list itself does not provide this info, right?

**Comment by Tarotis** [comment]
No, thats from the concepticon description: https://concepticon.clld.org/parameters/857

**Comment by mathildavz** [comment]
> @mathildavz, you can ask me questions here or on mattermost, if some of the explanations given here were not quite clear.
@LinguList Thank you for your step by step explanation! I think I was able to follow for now. I will take a closer look tomorrow, after I've reviewed Annika's file on "How to contribute" and Concepticon again, to see if I would be able to do this on my own. I'm sure some questions will pop up then.

**Comment by LinguList** [comment]
Ah, thanks, @Tarotis. The definitions do not need to be taken at face value in all cases. We also refine them. More important is the examples. You will see that most cases where you have German "Stein" really are linked to STONE. So I consider this the most consistent solution.

**Comment by Tarotis** [comment]
I have now implemented all the changes and unlinked the necessary concepts.

**Comment by LinguList** [comment]
A last request, can you please run the command:

```
$ concepticon check Nordenskiold-1905-50
```
and report the results here?

**Comment by Tarotis** [comment]
concepticondata/conceptlists/Nordenskioeld-1905-50.tsv
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                          NUMBER  GLOSS
----------------  ---------  ------------------------  --------  -------------------------
                         24  Nordenskioeld-1905-50-23        23  pauchi (chicken)
                         38  Nordenskioeld-1905-50-37        37  cotton shirt
                         39  Nordenskioeld-1905-50-38        38  headband made of feathers
                         44  Nordenskioeld-1905-50-43        43  stearin candle
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
Check: valid_concepticon_id
  CONCEPTICON_ID    LINE_NO  ID                          NUMBER  GLOSS
----------------  ---------  ------------------------  --------  -------
             927         20  Nordenskioeld-1905-50-19        19  manioc

**Comment by Tarotis** [comment]
Whats the problem with manioc? Should I use `Cassava` instead? Then I would definitely create an issue for the description, as it is specifically only for the pulp made out of the plant, and not for the root vegetable itself.

**Comment by LinguList** [comment]
I now gave one favorable review, so you can merge the PR, @Tarotis

**Comment by LinguList** [comment]
Thanks for the nice work!

**Pull request merged**
