### PR TITLE
Add Zhong-2022 Sensorimotor norms for Chinese

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [X] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR adds Sensorimotor norms for 664 Chinese words.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@LinguList  Would you moderate/review this PR?

I also added the list to a Google Sheet with duplicates in the English translation highlighted and a column for comments: https://docs.google.com/spreadsheets/d/1FLkLzk6_Q1bYL4OjCx_BLcPS6-zathLeDWXvWJalIBA/edit?usp=sharing

<details><summary>Concepticon check</summary>
<p>

```
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                    NUMBER  GLOSS
----------------  ---------  ------------------  --------  -----------------------------------
                          4  Zhong-2022-664-3           3  action
                          5  Zhong-2022-664-4           4  Pipa
                          6  Zhong-2022-664-5           5  speak; speech
                          7  Zhong-2022-664-6           6  drama
                          8  Zhong-2022-664-7           7  Chinese opera
                          9  Zhong-2022-664-8           8  performance
                         10  Zhong-2022-664-9           9  talk
                         13  Zhong-2022-664-12         12  opera
                         16  Zhong-2022-664-15         15  jazz
                         17  Zhong-2022-664-16         16  pour_out
                         18  Zhong-2022-664-17         17  greeting
                         19  Zhong-2022-664-18         18  pedestrian
                         20  Zhong-2022-664-19         19  inspiration
                         21  Zhong-2022-664-20         20  smile
                         24  Zhong-2022-664-23         23  video
                         25  Zhong-2022-664-24         24  (facial) expression
                         26  Zhong-2022-664-25         25  theater and drama
                         27  Zhong-2022-664-26         26  hot pot
                         28  Zhong-2022-664-27         27  report
                         29  Zhong-2022-664-28         28  thinking
                         30  Zhong-2022-664-29         29  homework
                         31  Zhong-2022-664-30         30  record
                         32  Zhong-2022-664-31         31  show
                         33  Zhong-2022-664-32         32  greeting
                         34  Zhong-2022-664-33         33  Peking Opera
                         36  Zhong-2022-664-35         35  discuss
                         37  Zhong-2022-664-36         36  commentary
                         38  Zhong-2022-664-37         37  football
                         39  Zhong-2022-664-38         38  dialogue
                         41  Zhong-2022-664-40         40  delicacy
                         44  Zhong-2022-664-43         43  tricks
                         45  Zhong-2022-664-44         44  dessert
                         46  Zhong-2022-664-45         45  script
                         49  Zhong-2022-664-48         48  confession
                         50  Zhong-2022-664-49         49  cuisine
                         51  Zhong-2022-664-50         50  momentum
                         53  Zhong-2022-664-52         52  lecture
                         55  Zhong-2022-664-54         54  piano
                         56  Zhong-2022-664-55         55  confession
                         57  Zhong-2022-664-56         56  impression
                         59  Zhong-2022-664-58         58  actor's lines
                         60  Zhong-2022-664-59         59  bright eyes of a beautiful woman
                         62  Zhong-2022-664-61         61  propaganda
                         63  Zhong-2022-664-62         62  gongs and drums
                         64  Zhong-2022-664-63         63  fragrance
                         67  Zhong-2022-664-66         66  glory and splendor
                         68  Zhong-2022-664-67         67  affection
                         69  Zhong-2022-664-68         68  subtitle
                         72  Zhong-2022-664-71         71  magic arts
                         74  Zhong-2022-664-73         73  body figure
                         75  Zhong-2022-664-74         74  image
                         78  Zhong-2022-664-77         77  concept
                         80  Zhong-2022-664-79         79  introspect
                         81  Zhong-2022-664-80         80  pushfulness
                         82  Zhong-2022-664-81         81  cherry blossoms
                         83  Zhong-2022-664-82         82  debate
                         84  Zhong-2022-664-83         83  behind
                         85  Zhong-2022-664-84         84  refined interest
                         86  Zhong-2022-664-85         85  look forward to
                         87  Zhong-2022-664-86         86  looks
                         88  Zhong-2022-664-87         87  applause
                         89  Zhong-2022-664-88         88  consciousness
                         90  Zhong-2022-664-89         89  hospitality
                         91  Zhong-2022-664-90         90  melody
                         92  Zhong-2022-664-91         91  potential
                         93  Zhong-2022-664-92         92  pressure
                         94  Zhong-2022-664-93         93  wisdom
                         95  Zhong-2022-664-94         94  description
                         96  Zhong-2022-664-95         95  poster
                         99  Zhong-2022-664-98         98  drama
                        100  Zhong-2022-664-99         99  dynamic
                        102  Zhong-2022-664-101       101  nursery rhymes
                        103  Zhong-2022-664-102       102  tacit understanding
                        104  Zhong-2022-664-103       103  coaching
                        105  Zhong-2022-664-104       104  scenery
                        106  Zhong-2022-664-105       105  program
                        108  Zhong-2022-664-107       107  phantom
                        109  Zhong-2022-664-108       108  humorous
                        110  Zhong-2022-664-109       109  figure
                        111  Zhong-2022-664-110       110  textbook
                        112  Zhong-2022-664-111       111  delicacy
                        113  Zhong-2022-664-112       112  discussion
                        114  Zhong-2022-664-113       113  exhibition
                        115  Zhong-2022-664-114       114  notes
                        117  Zhong-2022-664-116       116  discuss
                        118  Zhong-2022-664-117       117  film
                        120  Zhong-2022-664-119       119  around
                        122  Zhong-2022-664-121       121  fantasy
                        123  Zhong-2022-664-122       122  stimulate
                        125  Zhong-2022-664-124       124  comfort
                        126  Zhong-2022-664-125       125  works
                        127  Zhong-2022-664-126       126  way
                        128  Zhong-2022-664-127       127  recite
                        130  Zhong-2022-664-129       129  sea view
                        132  Zhong-2022-664-131       131  meditation
                        133  Zhong-2022-664-132       132  hallucination
                        134  Zhong-2022-664-133       133  enlighten
                        135  Zhong-2022-664-134       134  bondage
                        136  Zhong-2022-664-135       135  compliment
                        137  Zhong-2022-664-136       136  narrate
                        138  Zhong-2022-664-137       137  signal
                        139  Zhong-2022-664-138       138  sea of ​​clouds
                        140  Zhong-2022-664-139       139  view
                        141  Zhong-2022-664-140       140  fishy
                        143  Zhong-2022-664-142       142  fireworks
                        144  Zhong-2022-664-143       143  dumplings
                        147  Zhong-2022-664-146       146  melancholy
                        148  Zhong-2022-664-147       147  video
                        151  Zhong-2022-664-150       150  authentic
                        152  Zhong-2022-664-151       151  secret trouble
                        153  Zhong-2022-664-152       152  strategy
                        154  Zhong-2022-664-153       153  sentiment
                        156  Zhong-2022-664-155       155  preaching
                        157  Zhong-2022-664-156       156  fantasy
                        158  Zhong-2022-664-157       157  musical instrument
                        161  Zhong-2022-664-160       160  awareness
                        162  Zhong-2022-664-161       161  simulation
                        166  Zhong-2022-664-165       165  temptation
                        167  Zhong-2022-664-166       166  debate
                        168  Zhong-2022-664-167       167  lament
                        169  Zhong-2022-664-168       168  after rhyme
                        172  Zhong-2022-664-171       171  moan
                        174  Zhong-2022-664-173       173  perplexed
                        176  Zhong-2022-664-175       175  speech
                        178  Zhong-2022-664-177       177  newspaper and magazine
                        181  Zhong-2022-664-180       180  witchcraft
                        183  Zhong-2022-664-182       182  singing
                        185  Zhong-2022-664-184       184  a view of sb's back
                        186  Zhong-2022-664-185       185  magazine
                        187  Zhong-2022-664-186       186  quality
                        188  Zhong-2022-664-187       187  homesickness
                        190  Zhong-2022-664-189       189  everything
                        192  Zhong-2022-664-191       191  nagging
                        193  Zhong-2022-664-192       192  chorus
                        194  Zhong-2022-664-193       193  goal keeper
                        196  Zhong-2022-664-195       195  record
                        197  Zhong-2022-664-196       196  comics
                        199  Zhong-2022-664-198       198  keyboard
                        200  Zhong-2022-664-199       199  ask questions
                        201  Zhong-2022-664-200       200  temptress
                        202  Zhong-2022-664-201       201  wisdom
                        203  Zhong-2022-664-202       202  attachment
                        204  Zhong-2022-664-203       203  modeling
                        207  Zhong-2022-664-206       206  mind
                        208  Zhong-2022-664-207       207  magnificent feat
                        209  Zhong-2022-664-208       208  toil
                        211  Zhong-2022-664-210       210  soundtrack
                        214  Zhong-2022-664-213       213  difficulty
                        215  Zhong-2022-664-214       214  statement
                        217  Zhong-2022-664-216       216  spirituality
                        218  Zhong-2022-664-217       217  hypocritical
                        219  Zhong-2022-664-218       218  practice
                        220  Zhong-2022-664-219       219  trend
                        221  Zhong-2022-664-220       220  position
                        225  Zhong-2022-664-224       224  concern
                        226  Zhong-2022-664-225       225  ferocious ghost
                        228  Zhong-2022-664-227       227  all around
                        229  Zhong-2022-664-228       228  repertoire
                        231  Zhong-2022-664-230       230  purgatory
                        233  Zhong-2022-664-232       232  sustenance
                        234  Zhong-2022-664-233       233  trend of thought
                        235  Zhong-2022-664-234       234  awakening
                        236  Zhong-2022-664-235       235  humble opinion
                        237  Zhong-2022-664-236       236  look forward to
                        238  Zhong-2022-664-237       237  surroundings
                        239  Zhong-2022-664-238       238  explanation
                        240  Zhong-2022-664-239       239  contour
                        243  Zhong-2022-664-242       242  aroma
                        245  Zhong-2022-664-244       244  comment
                        249  Zhong-2022-664-248       248  elaboration
                        250  Zhong-2022-664-249       249  course
                        252  Zhong-2022-664-251       251  pronunciation
                        254  Zhong-2022-664-253       253  function
                        255  Zhong-2022-664-254       254  horoscope
                        256  Zhong-2022-664-255       255  frequency
                        257  Zhong-2022-664-256       256  love song
                        261  Zhong-2022-664-260       260  natural bonds and ethical relations
                        262  Zhong-2022-664-261       261  old time
                        266  Zhong-2022-664-265       265  fine view
                        267  Zhong-2022-664-266       266  broadcast
                        268  Zhong-2022-664-267       267  situation
                        269  Zhong-2022-664-268       268  melons and fruits
                        270  Zhong-2022-664-269       269  scheming
                        272  Zhong-2022-664-271       271  discourse
                        273  Zhong-2022-664-272       272  bad smell
                        274  Zhong-2022-664-273       273  exhibits
                        276  Zhong-2022-664-275       275  style
                        277  Zhong-2022-664-276       276  tune
                        278  Zhong-2022-664-277       277  slogan
                        280  Zhong-2022-664-279       279  enlightenment
                        281  Zhong-2022-664-280       280  suspect
                        282  Zhong-2022-664-281       281  power and influence
                        283  Zhong-2022-664-282       282  trace
                        284  Zhong-2022-664-283       283  abuse of power
                        286  Zhong-2022-664-285       285  supernatural power
                        287  Zhong-2022-664-286       286  bring shame on
                        288  Zhong-2022-664-287       287  suspicious
                        289  Zhong-2022-664-288       288  long-cherished wish
                        290  Zhong-2022-664-289       289  artistic conception
                        291  Zhong-2022-664-290       290  conduct
                        292  Zhong-2022-664-291       291  totalitarian
                        293  Zhong-2022-664-292       292  explore
                        294  Zhong-2022-664-293       293  condition
                        295  Zhong-2022-664-294       294  conventional verbal exchanges
                        296  Zhong-2022-664-295       295  craft
                        297  Zhong-2022-664-296       296  scene
                        298  Zhong-2022-664-297       297  report
                        299  Zhong-2022-664-298       298  tweet
                        300  Zhong-2022-664-299       299  dialogue
                        303  Zhong-2022-664-302       302  recording
                        304  Zhong-2022-664-303       303  pace
                        305  Zhong-2022-664-304       304  seafood
                        306  Zhong-2022-664-305       305  draw (in a game)
                        307  Zhong-2022-664-306       306  (personal) quality
                        309  Zhong-2022-664-308       308  disadvantage
                        310  Zhong-2022-664-309       309  introduction
                        311  Zhong-2022-664-310       310  celebrity
                        312  Zhong-2022-664-311       311  murderous look
                        313  Zhong-2022-664-312       312  philosophy
                        314  Zhong-2022-664-313       313  adjustment
                        316  Zhong-2022-664-315       315  determination
                        318  Zhong-2022-664-317       317  scene
                        319  Zhong-2022-664-318       318  material object
                        320  Zhong-2022-664-319       319  talk
                        324  Zhong-2022-664-323       323  explaination
                        326  Zhong-2022-664-325       325  chirping of cicada
                        327  Zhong-2022-664-326       326  aircraft
                        329  Zhong-2022-664-328       328  conception
                        330  Zhong-2022-664-329       329  innovation
                        331  Zhong-2022-664-330       330  eschatology
                        332  Zhong-2022-664-331       331  fashion
                        333  Zhong-2022-664-332       332  resistance
                        334  Zhong-2022-664-333       333  distracting thoughts
                        335  Zhong-2022-664-334       334  category
                        336  Zhong-2022-664-335       335  rise and fall
                        337  Zhong-2022-664-336       336  opinion
                        340  Zhong-2022-664-339       339  album
                        341  Zhong-2022-664-340       340  broad sense
                        342  Zhong-2022-664-341       341  rhythm
                        343  Zhong-2022-664-342       342  advertising
                        345  Zhong-2022-664-344       344  status
                        346  Zhong-2022-664-345       345  blue sky
                        347  Zhong-2022-664-346       346  backbone
                        348  Zhong-2022-664-347       347  internal strength
                        349  Zhong-2022-664-348       348  essence
                        350  Zhong-2022-664-349       349  virility
                        353  Zhong-2022-664-352       352  rebroadcast
                        354  Zhong-2022-664-353       353  peculiar smell
                        355  Zhong-2022-664-354       354  blog
                        356  Zhong-2022-664-355       355  evil thoughts
                        357  Zhong-2022-664-356       356  blessing
                        363  Zhong-2022-664-362       362  instinct
                        364  Zhong-2022-664-363       363  virtue
                        365  Zhong-2022-664-364       364  sigh
                        366  Zhong-2022-664-365       365  lens
                        368  Zhong-2022-664-367       367  radio station
                        369  Zhong-2022-664-368       368  mercy
                        370  Zhong-2022-664-369       369  text
                        371  Zhong-2022-664-370       370  scenery
                        373  Zhong-2022-664-372       372  style of painting
                        374  Zhong-2022-664-373       373  righteousness
                        375  Zhong-2022-664-374       374  chance encounter
                        376  Zhong-2022-664-375       375  charm
                        377  Zhong-2022-664-376       376  reflection
                        382  Zhong-2022-664-381       381  count on
                        383  Zhong-2022-664-382       382  one's character
                        384  Zhong-2022-664-383       383  topic
                        386  Zhong-2022-664-385       385  significance
                        388  Zhong-2022-664-387       387  lingering charm
                        389  Zhong-2022-664-388       388  discipline
                        390  Zhong-2022-664-389       389  legend
                        391  Zhong-2022-664-390       390  one's duty
                        392  Zhong-2022-664-391       391  mentality
                        393  Zhong-2022-664-392       392  degenerate
                        395  Zhong-2022-664-394       394  night view
                        397  Zhong-2022-664-396       396  moon cake
                        400  Zhong-2022-664-399       399  throbbing
                        401  Zhong-2022-664-400       400  speculation
                        402  Zhong-2022-664-401       401  upsurge
                        403  Zhong-2022-664-402       402  at the beginning
                        404  Zhong-2022-664-403       403  mission
                        406  Zhong-2022-664-405       405  metaphysics
                        407  Zhong-2022-664-406       406  cause and effect
                        410  Zhong-2022-664-409       409  sophistry
                        411  Zhong-2022-664-410       410  answer
                        412  Zhong-2022-664-411       411  short film
                        413  Zhong-2022-664-412       412  temperament
                        414  Zhong-2022-664-413       413  data
                        415  Zhong-2022-664-414       414  metaphor
                        418  Zhong-2022-664-417       417  acrimonious
                        419  Zhong-2022-664-418       418  bright light
                        420  Zhong-2022-664-419       419  great master
                        421  Zhong-2022-664-420       420  piercingly cold
                        422  Zhong-2022-664-421       421  patience
                        423  Zhong-2022-664-422       422  group sentiment
                        424  Zhong-2022-664-423       423  pronunciation
                        425  Zhong-2022-664-424       424  experience
                        426  Zhong-2022-664-425       425  all evil
                        427  Zhong-2022-664-426       426  opportunity
                        428  Zhong-2022-664-427       427  features
                        429  Zhong-2022-664-428       428  innovation
                        434  Zhong-2022-664-433       433  stock
                        436  Zhong-2022-664-435       435  speaker
                        438  Zhong-2022-664-437       437  opportunity
                        439  Zhong-2022-664-438       438  internal force
                        440  Zhong-2022-664-439       439  romantic charm
                        441  Zhong-2022-664-440       440  (literary or artistic) style
                        442  Zhong-2022-664-441       441  situation
                        443  Zhong-2022-664-442       442  illusion
                        444  Zhong-2022-664-443       443  development
                        445  Zhong-2022-664-444       444  dirty work
                        446  Zhong-2022-664-445       445  tone of voice
                        447  Zhong-2022-664-446       446  prelude
                        448  Zhong-2022-664-447       447  accompaniment
                        449  Zhong-2022-664-448       448  starry sky
                        451  Zhong-2022-664-450       450  convert
                        453  Zhong-2022-664-452       452  (evil) intentions
                        454  Zhong-2022-664-453       453  temperature
                        455  Zhong-2022-664-454       454  atmosphere
                        456  Zhong-2022-664-455       455  form
                        458  Zhong-2022-664-457       457  classic
                        460  Zhong-2022-664-459       459  foresight
                        461  Zhong-2022-664-460       460  running water
                        462  Zhong-2022-664-461       461  fiction
                        463  Zhong-2022-664-462       462  preaching
                        464  Zhong-2022-664-463       463  wild ambition
                        465  Zhong-2022-664-464       464  fragrance
                        466  Zhong-2022-664-465       465  table of contents
                        467  Zhong-2022-664-466       466  prophecy
                        468  Zhong-2022-664-467       467  situation
                        469  Zhong-2022-664-468       468  development
                        470  Zhong-2022-664-469       469  degenerate
                        471  Zhong-2022-664-470       470  view
                        474  Zhong-2022-664-473       473  vitality
                        476  Zhong-2022-664-475       475  source
                        478  Zhong-2022-664-477       477  prestige
                        479  Zhong-2022-664-478       478  degree
                        480  Zhong-2022-664-479       479  wonderland
                        481  Zhong-2022-664-480       480  foresight
                        482  Zhong-2022-664-481       481  morale
                        483  Zhong-2022-664-482       482  aromatic
                        484  Zhong-2022-664-483       483  image
                        488  Zhong-2022-664-487       487  hypothesis
                        490  Zhong-2022-664-489       489  style of writing
                        492  Zhong-2022-664-491       491  potential
                        493  Zhong-2022-664-492       492  drastic changes
                        494  Zhong-2022-664-493       493  doctrine of the mean
                        496  Zhong-2022-664-495       495  substance
                        498  Zhong-2022-664-497       497  composition
                        499  Zhong-2022-664-498       498  lamplight
                        502  Zhong-2022-664-501       501  decency
                        503  Zhong-2022-664-502       502  text
                        504  Zhong-2022-664-503       503  texture
                        505  Zhong-2022-664-504       504  curve
                        506  Zhong-2022-664-505       505  name list
                        507  Zhong-2022-664-506       506  spring rain
                        508  Zhong-2022-664-507       507  situation
                        509  Zhong-2022-664-508       508  ideal
                        510  Zhong-2022-664-509       509  talent
                        511  Zhong-2022-664-510       510  loyalty
                        514  Zhong-2022-664-513       513  diary
                        516  Zhong-2022-664-515       515  morality
                        519  Zhong-2022-664-518       518  ego
                        520  Zhong-2022-664-519       519  false alarm
                        521  Zhong-2022-664-520       520  talent
                        522  Zhong-2022-664-521       521  proposal
                        523  Zhong-2022-664-522       522  screen
                        524  Zhong-2022-664-523       523  English
                        525  Zhong-2022-664-524       524  visionary hope
                        527  Zhong-2022-664-526       526  tolerance
                        528  Zhong-2022-664-527       527  theme
                        529  Zhong-2022-664-528       528  convert
                        530  Zhong-2022-664-529       529  universally
                        531  Zhong-2022-664-530       530  ambition
                        532  Zhong-2022-664-531       531  topic
                        533  Zhong-2022-664-532       532  acerbity
                        534  Zhong-2022-664-533       533  soul
                        535  Zhong-2022-664-534       534  determined
                        536  Zhong-2022-664-535       535  relationship
                        537  Zhong-2022-664-536       536  holy words
                        538  Zhong-2022-664-537       537  noble family
                        539  Zhong-2022-664-538       538  CD
                        540  Zhong-2022-664-539       539  Reiki
                        541  Zhong-2022-664-540       540  incarnation
                        542  Zhong-2022-664-541       541  good and evil
                        544  Zhong-2022-664-543       543  experience
                        545  Zhong-2022-664-544       544  suggestion
                        546  Zhong-2022-664-545       545  certificate
                        547  Zhong-2022-664-546       546  honor and disgrace
                        548  Zhong-2022-664-547       547  Zongzi
                        549  Zhong-2022-664-548       548  tension
                        550  Zhong-2022-664-549       549  meaning
                        551  Zhong-2022-664-550       550  virtue
                        553  Zhong-2022-664-552       552  catastrophe
                        556  Zhong-2022-664-555       555  hand feeling
                        557  Zhong-2022-664-556       556  contract
                        559  Zhong-2022-664-558       558  characterization
                        560  Zhong-2022-664-559       559  some kind
                        561  Zhong-2022-664-560       560  will
                        563  Zhong-2022-664-562       562  information
                        564  Zhong-2022-664-563       563  situation
                        565  Zhong-2022-664-564       564  creation
                        566  Zhong-2022-664-565       565  lingering interest
                        568  Zhong-2022-664-567       567  red leaves
                        569  Zhong-2022-664-568       568  original intention
                        570  Zhong-2022-664-569       569  keynote
                        571  Zhong-2022-664-570       570  taboo
                        572  Zhong-2022-664-571       571  representation
                        573  Zhong-2022-664-572       572  half a lifetime
                        576  Zhong-2022-664-575       575  glory
                        577  Zhong-2022-664-576       576  viewpoint
                        578  Zhong-2022-664-577       577  origin
                        579  Zhong-2022-664-578       578  mystery
                        580  Zhong-2022-664-579       579  current situation
                        581  Zhong-2022-664-580       580  amorous feelings
                        583  Zhong-2022-664-582       582  permanent
                        584  Zhong-2022-664-583       583  inducement
                        585  Zhong-2022-664-584       584  afterlife
                        587  Zhong-2022-664-586       586  deeds
                        588  Zhong-2022-664-587       587  content
                        589  Zhong-2022-664-588       588  web page
                        590  Zhong-2022-664-589       589  magic bullet
                        591  Zhong-2022-664-590       590  grievance
                        592  Zhong-2022-664-591       591  retouch
                        593  Zhong-2022-664-592       592  ethics
                        594  Zhong-2022-664-593       593  situation
                        595  Zhong-2022-664-594       594  circumstances
                        596  Zhong-2022-664-595       595  experience
                        598  Zhong-2022-664-597       597  file
                        601  Zhong-2022-664-600       600  prestige
                        602  Zhong-2022-664-601       601  human world
                        603  Zhong-2022-664-602       602  democracy
                        604  Zhong-2022-664-603       603  holy spirit
                        605  Zhong-2022-664-604       604  blessing
                        606  Zhong-2022-664-605       605  another day
                        607  Zhong-2022-664-606       606  natural instincts
                        608  Zhong-2022-664-607       607  symbol
                        610  Zhong-2022-664-609       609  grace
                        611  Zhong-2022-664-610       610  opportunity
                        613  Zhong-2022-664-612       612  sea ​​of ​​bitterness
                        614  Zhong-2022-664-613       613  adversity
                        615  Zhong-2022-664-614       614  myth
                        618  Zhong-2022-664-617       617  moment
                        619  Zhong-2022-664-618       618  material
                        620  Zhong-2022-664-619       619  chance
                        622  Zhong-2022-664-621       621  factor
                        623  Zhong-2022-664-622       622  indigenous method
                        624  Zhong-2022-664-623       623  spare power
                        625  Zhong-2022-664-624       624  data
                        626  Zhong-2022-664-625       625  conscience
                        628  Zhong-2022-664-627       627  title
                        629  Zhong-2022-664-628       628  merits and virtues
                        630  Zhong-2022-664-629       629  intrinsic
                        631  Zhong-2022-664-630       630  wide gap
                        633  Zhong-2022-664-632       632  rumor
                        634  Zhong-2022-664-633       633  eternal
                        635  Zhong-2022-664-634       634  inside story
                        636  Zhong-2022-664-635       635  comprehension by intuition
                        638  Zhong-2022-664-637       637  realm
                        640  Zhong-2022-664-639       639  breadth of mind
                        641  Zhong-2022-664-640       640  ancient times
                        642  Zhong-2022-664-641       641  heartbeat
                        643  Zhong-2022-664-642       642  consequence
                        644  Zhong-2022-664-643       643  afflict with great suffering
                        645  Zhong-2022-664-644       644  variable
                        646  Zhong-2022-664-645       645  genius
                        648  Zhong-2022-664-647       647  philosophy
                        649  Zhong-2022-664-648       648  version
                        650  Zhong-2022-664-649       649  safeline
                        651  Zhong-2022-664-650       650  attributes
                        653  Zhong-2022-664-652       652  nonsense
                        656  Zhong-2022-664-655       655  original sin
                        657  Zhong-2022-664-656       656  accent
                        658  Zhong-2022-664-657       657  integrity in one's later years
                        659  Zhong-2022-664-658       658  white color
                        661  Zhong-2022-664-660       660  moral quality
                        662  Zhong-2022-664-661       661  origin
                        663  Zhong-2022-664-662       662  sentence
                        665  Zhong-2022-664-664       664  meantime
1017                    146  Zhong-2022-664-145       145  appearance
1017                    191  Zhong-2022-664-190       190  appearance
1162                    380  Zhong-2022-664-379       379  intention
1162                    457  Zhong-2022-664-456       456  intention
1175                    180  Zhong-2022-664-179       179  ghost
1175                    408  Zhong-2022-664-407       407  ghost
1560                    131  Zhong-2022-664-130       130  face
1560                    325  Zhong-2022-664-324       324  face
1592                    487  Zhong-2022-664-486       486  chest
1592                    632  Zhong-2022-664-631       631  chest
1609                    173  Zhong-2022-664-172       172  idea
1609                    177  Zhong-2022-664-176       176  opinion
1609                    338  Zhong-2022-664-337       337  idea
1609                    452  Zhong-2022-664-451       451  idea
1609                    600  Zhong-2022-664-599       599  idea
1613                    323  Zhong-2022-664-322       322  color
1613                    399  Zhong-2022-664-398       398  colour
1688                    107  Zhong-2022-664-106       106  fate
1688                    145  Zhong-2022-664-144       144  fate
2295                    230  Zhong-2022-664-229       229  sunset
2295                    259  Zhong-2022-664-258       258  sunset
2295                    321  Zhong-2022-664-320       320  sunset
2342                    149  Zhong-2022-664-148       148  landscape
2342                    344  Zhong-2022-664-343       343  landscape
2526                    263  Zhong-2022-664-262       262  power
2526                    315  Zhong-2022-664-314       314  power
2573                     65  Zhong-2022-664-64         64  feeling
2573                    459  Zhong-2022-664-458       458  emotion
2938                    317  Zhong-2022-664-316       316  flavor
2938                    352  Zhong-2022-664-351       351  flavor
2938                    512  Zhong-2022-664-511       511  flavor
2944                    142  Zhong-2022-664-141       141  call
2944                    433  Zhong-2022-664-432       432  call
2950                    232  Zhong-2022-664-231       231  meaning
2950                    416  Zhong-2022-664-415       415  meaning
2964                    302  Zhong-2022-664-301       301  news
2964                    359  Zhong-2022-664-358       358  news
2988                    242  Zhong-2022-664-241       241  patterns
2988                    655  Zhong-2022-664-654       654  pattern
3049                    248  Zhong-2022-664-247       247  courage
3049                    381  Zhong-2022-664-380       380  courage
3304                    477  Zhong-2022-664-476       476  photo
3304                    599  Zhong-2022-664-598       598  photo
3897                    351  Zhong-2022-664-350       350  nature
3897                    652  Zhong-2022-664-651       651  nature
53                       61  Zhong-2022-664-60         60  spirit
53                      165  Zhong-2022-664-164       164  spirit
642                      48  Zhong-2022-664-47         47  music
642                      97  Zhong-2022-664-96         96  music
720                     260  Zhong-2022-664-259       259  luck
720                     664  Zhong-2022-664-663       663  good fortune
763                      77  Zhong-2022-664-76         76  skin
763                     472  Zhong-2022-664-471       471  skin
811                     517  Zhong-2022-664-516       516  soul
811                     627  Zhong-2022-664-626       626  soul
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK

```

</p>
</details>

**Comment by LinguList** [comment]
Yes, I'll monitor it!

**Comment by AnnikaTjuka** [comment]
The list is already available in a Google sheet: 

> I also added the list to a Google Sheet with duplicates in the English translation highlighted and a column for comments: https://docs.google.com/spreadsheets/d/1FLkLzk6_Q1bYL4OjCx_BLcPS6-zathLeDWXvWJalIBA/edit?usp=sharing

**Comment by LinguList** [comment]
Sorry had not seen this earlier! Will check this week!

**Comment by LinguList** [comment]
I deleted many duplicates now. Mostly style problems (only occurs in proverbs, vs. daily life, pejorative, etc.). There is the chance that I missed something, but rather I missed possible mappings, than allowed bad mappings. So from my viewpoint, this can be merged when updated with what I just adjusted there. Some duplicates left are allowed, even the data contains internal duplicates, like "meaning", and "sunset", where a word is swapped with morphemes.

**Comment by AnnikaTjuka** [comment]
Many thanks! I'll update the mappings tomorrow at the latest.

**Review by LinguList — APPROVED** [review]

**Comment by AnnikaTjuka** [comment]
I updated the mappings based on the Google sheet and will merge now.

**Pull request merged**
