### PR TITLE
Add KochGrunberg-1914-821

### PR DESCRIPTION
**Pull request by MottaAM**
# Pull request checklist

- [ X] add new concept list
- [ X] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

### CODE REVIEW

**Comment by LinguList** [comment]
@MottaAM, could you also share the output of the command `concepticon check KochGrunberg-1914-809`, as this provides interesting statistics on duplicate words?

**Comment by LinguList** [comment]
We also need to check the translations (German is the original), e.g., KochGrunberg-1914-809-233 translates *Einbaum* as "tree", but an Einbaum, a one-tree, is a boat that was made from one tree. It is a canoe.

**Comment by LinguList** [comment]
@MottaAM, the translations in English are made by you, so they should be called GLOSS, not ENGLISH. This is some rule, for all English translations we make. For other languages we don't have the rule. But for Portuguese, you should maybe add in the main text presenting the list, that the translation was added.

**Comment by LinguList** [comment]
One more request: can we plase not start English words with capital letters, but rather small, as we typically do? You can do so automatically later, but I'd like to have this thoroughly checked, as it helps us to check the translations again anyway.

**Comment by LinguList** [comment]
I did this in the google sheet, also for Portuguese. Only in German, capitals are part of the orthography.

**Comment by AnnikaTjuka** [comment]
@LinguList Sure, I will review the list.

**Comment by MottaAM** [comment]
> @MottaAM, could you also share the output of the command `concepticon check KochGrunberg-1914-809`, as this provides interesting statistics on duplicate words?

Sure! Here it is:

```
1033                    718  KochGrunberg-1914-809-717       717  Grind
1033                    782  KochGrunberg-1914-809-781       781  Grind
1937                    700  KochGrunberg-1914-809-699       699  There
1937                    702  KochGrunberg-1914-809-701       701  There
197                     644  KochGrunberg-1914-809-643       643  Other
197                     648  KochGrunberg-1914-809-647       647  Other
2133                    746  KochGrunberg-1914-809-745       745  Strike or beat
2133                    781  KochGrunberg-1914-809-780       780  Strike or beat
2382                    688  KochGrunberg-1914-809-687       687  Blue
2382                    689  KochGrunberg-1914-809-688       688  Green
664                     253  KochGrunberg-1914-809-252       252  Resin
664                     577  KochGrunberg-1914-809-576       576  Resin
906                     234  KochGrunberg-1914-809-233       233  Tree
906                     570  KochGrunberg-1914-809-569       569  Tree
937                     442  KochGrunberg-1914-809-441       441  Bird (= passarinho)
937                     471  KochGrunberg-1914-809-470       470  Bird
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
Check: valid_concepticon_id
  CONCEPTICON_ID    LINE_NO  ID                           NUMBER  GLOSS
----------------  ---------  -------------------------  --------  -------
             927        584  KochGrunberg-1914-809-583       583  Manioc
```

**Comment by LinguList** [comment]
That helps: all instances where the English translation is the same, but the German is not should be checked and disambiguated. I'll add code to color those automatically int eh google sheet.

**Comment by LinguList** [comment]
Perfect, many thanks, I saw them. @MottaAM, can you please already check them and if you answered a point, just give a noote? I'll then check one more time, and we add teh list!

**Comment by LinguList** [comment]
@MottaAM, please let us know once you have looked at the Google Doc and then also integrated it here (with comments there resolved of course)

**Comment by LinguList** [comment]
I suggest, you delete the comment, e.g., if you checked a translation to Portuguese, etc. So we know nothing is left.

**Comment by LinguList** [comment]
@MottaAM, one more question: do you follow the order of the article by Koch Grunberg, for the numbering, or are the numbers later introduced? I am asking, since Koch is giving semantic fields which are not in this list.

**Comment by MottaAM** [comment]
> @MottaAM, one more question: do you follow the order of the article by Koch Grunberg, for the numbering, or are the numbers later introduced? I am asking, since Koch is giving semantic fields which are not in this list.

I copied in the same order the words were in the original list

**Comment by LinguList** [comment]
But your list now is alphabetical?

**Comment by LinguList** [comment]
No, you are right, sorry! So @MottaAM, can I ask you one more favor: can you ADD the Categories in the original article?

**Comment by LinguList** [comment]
Screenshot_2022-04-14_07-39-48

Check this screenshot. What I'd ask to do here is adding two columns for all words beyond this (Fisch, etc.), it is from the 1915 article, but the 1913 also has this structure:

1. column with page number (128), call it PAGE added to all individual concepts, redundantly
2. column with semantic category, call it SEMANTIC_CATEGORY, with `H. Fische, Reptilien` as the content for all concepts (again redundantly, a bit of copy-pasting).

**Comment by LinguList** [comment]
We typically try to model concept lists in much detail to how we find them, so I think this would be very useful here.

**Comment by MottaAM** [comment]
> Screenshot_2022-04-14_07-39-48
> 
> Check this screenshot. What I'd ask to do here is adding two columns for all words beyond this (Fisch, etc.), it is from the 1915 article, but the 1913 also has this structure:
> 
> 1. column with page number (128), call it PAGE added to all individual concepts, redundantly
> 2. column with semantic category, call it SEMANTIC_CATEGORY, with `H. Fische, Reptilien` as the content for all concepts (again redundantly, a bit of copy-pasting).

Sure! I'm going to add them to the list! Also, I'm going to add the words of the Category `Zahlen` that I skipped

**Comment by LinguList** [comment]
Ah, this is important: do we also have the Zahlen in the lexibank dataset?

**Comment by LinguList** [comment]
Ah, and just add the columns to the google sheet, right? It is easiest 
to work there, and I can immediately check in case of questions.

**Comment by MottaAM** [comment]
> Ah, this is important: do we also have the Zahlen in the lexibank dataset?

we don't have it there. I have to add there too

**Comment by MottaAM** [comment]
Apparently there are sub-categories too. Should I add them?

**Comment by LinguList** [comment]
Yes, good idea!

**Comment by LinguList** [comment]
It would make sense to add it, in my impression.

**Comment by MottaAM** [comment]
image

I don't know if I should include that part in the list, since it talks about the morphology of the words and doesn't translate every word to German

Apart form that, I only have to look into the translation of a few words and change the name of the list to account for the new words added (there are 821 words now)

**Comment by LinguList** [comment]
I think you can leave this out. In the description of the concept list, you could add one sentence: "We have added all those entries from the original data where we can find a gloss with a concrete translation by the author, cases where only grammatical markers or other aspects not pertaining to the lexicon were discussed are thus not rendered here."

**Comment by LinguList** [comment]
@MottaAM, if you want us to react on updates, and double-check, leave a comment here, so we know we should have a look. I am saying this since I saw that you just updated something. Better always to remind the others, so we know when to look.

**Comment by MottaAM** [comment]
@LinguList, Sure! I'll remember to leave a comment. I tried to add the sentence you asked me to add and change the name of the list, but apparently it didn't work. 

Could you please help me with the translation of a few words in German? I left a comment next to the words I'm have trouble with in the google sheets list.

Also, I'm almost done adding the new words from the `Zahlen` category to the lexibank dataset. I'm going to upload the updated list there soon

**Comment by LinguList** [comment]
Sorry, @MottaAM, I was very busy with other things. I'll check this on Wednesday or Thursday and then get back to you.

**Comment by MottaAM** [comment]
No problem! Thank you for telling me. Until next week, I'll be a bit busy because of my finals, so I'll have less time to work on the list until then.

**Comment by LinguList** [comment]
@MottaAM, before we proceed, as you added more concepts, the number changed and must be changed int he other files (the name of the concept list). May I ask you to first do this, so no error turns up here anymore? Afterwards, if you informed me about the modification and we do not have the error (showing in read here), we can proceed by helping you with the final translations.

**Comment by MottaAM** [comment]
I changed the name of the files, @LinguList. After we are done correcting the list, I'll generate a new metadata file for it.

**Comment by LinguList** [comment]
Just checked the translations and modified them marginally in one case. I deleted comments to indicate we are done. So I look forward to the update, so we can finish this up then, @MottaAM

**Comment by MottaAM** [comment]
I uploaded the new list and the new metadata. I think we are done here, @LinguList

**Comment by LinguList** [comment]
All checks have passed, in my opinion, we can merge this now. @AnnikaTjuka, I'd let you have a final-final look and then merge.

**Comment by LinguList** [comment]
@MottaAM, can you paste your full name and affiliation here, so we list you as a coontributor to concepticon 2.6, which we'll release soon?

**Review by AnnikaTjuka — APPROVED** [review]
Looks good. Great work, @MottaAM !

**Comment by MottaAM** [comment]
Thank you, @AnnikaTjuka! Also, thank you for reviewing the list!

**Comment by MottaAM** [comment]
> @MottaAM, can you paste your full name and affiliation here, so we list you as a coontributor to concepticon 2.6, which we'll release soon?

Mateus Alves Motta
University of Brasília

**Pull request merged**
