### PR TITLE
pre-release 2.4.0-rc.1

### PR DESCRIPTION
**Pull request by xrotwang**
addresses #886

### CODE REVIEW

**Comment by xrotwang** [comment]
As far as I can see, the concepticon app data has never been under version control (it's excluded in `.gitignore`). Do you think this should be changed?

**Comment by LinguList** [comment]
Ah, I see, then we could in fact also delete the concepticon,json file? I tend to update it on https://digling.org/calc/concepticon/, and it goes into norare, but there I already have a recent version (and I added the full app, just for completeness, although we have to find a common policy then anyway, when we merge both datasets). 

And even more important, I just saw it: the app data is in `app/data`, so no need to delete, it has never been there.

**Comment by xrotwang** [comment]
Ok, I'll flesh out `concepticon citation` to also write a `.zenodo.json`, based on `CONTRIBTORS.md`, and add the result here.

**Comment by LinguList** [comment]
```
{
    "title": "Concepticon. A resource for the linking of concept lists",
    "creators": [
        {
            "name": "Johann-Mattis List"
        },
        {
            "name": "Christoph Rzymski"
        },
        {
            "name": "Simon Greenhill"
        },
        {
            "name": "Nathanael E. Schweikhard"
        },
        {
            "name": "Kristina Pianykh"
        },
        {
            "name": "Annika Tjuka"
        },
        {
            "name": "Mei-Shin Wu"
        },
        {
            "name": "Annika Tjuka"
        },
        {
            "name": "Robert Forkel"
        }
    ],
    "description": "<p>Cite the library as:</p>\n\n<blockquote>\n<p>List, J., C. Rzymski, S. Greenhill, N. Schweikhard, K. Pianykh, A. Tjuka, M. Wu, and R. Forkel (2020): Concepticon. A resource for the linking of concept lists. Version 2.4.0.beta. Max Planck Institute for the Science of Human History: Jena. https://concepticon.clld.org/.</p>\n</blockquote>",
    "access_right": "open",
    "keywords": [
        "linguistics",
        "cldf:Wordlist",
        "concept list"
    ],
    "license": {
        "id": "CC-BY-NC-4.0"
    },
    "contributors": [],
    "upload_type": "dataset",
    "communities": [
        {
            "identifier": "dighl"
        },
        {
            "identifer": "calc"
        }
    ]
}
```

**Comment by LinguList** [comment]
I just prepared this one. We could, of course, also list all contributors in contributors.md to this, may be even cooler for the future, so new contributors would then be added there as well to our zenodo.json?

**Comment by AnnikaTjuka** [comment]
@LinguList I'm listed twice in the "creators:" list. Should we add @CarolinHu instead:
```
 {
            "name": "Mei-Shin Wu"
        },
        {
            "name": "Carolin Hundt"
        },
        {
            "name": "Robert Forkel"
        }
```

**Comment by LinguList** [comment]
Carolin can be discussed for 2.4, your name should only appear once, I
copy-pasted the passages in json, so I mistakenly added you twice. For
this version, I'd leave it at the editors we had so far, we only take
new editors with a full release.

**Comment by xrotwang** [comment]
@LinguList where's the NC clause in the license coming from? We always had CC-BY, no?

**Comment by xrotwang** [comment]
@LinguList regarding @CarolinHu : I consider this a "release candidate" (hence the `-rc.1` suffix) for the 2.4 release. So technically, this **is** a full release. Now we could regard not adding new editors right now an oversight which will be fixed with the proper release - but if we already know she should be added then I'd do it now.

**Comment by LinguList** [comment]
sorry, delete it, this is from lingpy, but even there, we can probably
discard it. I just copypasted an older .zenodo.json, sorry

**Comment by LinguList** [comment]
That's exactly the discussion I wanted to avoid: that we openly discuss
these things, which we normally do in a quiet email session, where we
set up the order of authors (which may have to change also), and the like.

What is important to mention is that we may even consider other people
to be added to the editor's board this time, and we don't have the time
to discuss all of this now (and I may want to talk with people and
encourage them to help, etc.).

So I really would say: please let us just take the order and authors
from last time. If that's not possible, then we rather do not do a
release and ask people to check out a specific branch or git hash: all
after all it is just a paper we submit, if the paper was accepted, it
would be a different question, but we need to pass reviewers, and
editors, and we'll likely want to have another release anyway in three
months from now...

**Comment by xrotwang** [comment]
`.zenodo.json` is now created via `concepticon citation`.

**Comment by LinguList** [comment]
very cool!!!

**Comment by xrotwang** [comment]
ok, so then this is probably complete.

**Comment by LinguList** [comment]
so we can merge?

**Pull request merged**
