### PR TITLE
Klamer

### PR DESCRIPTION
**Pull request by LinguList**
# Pull request checklist

- [x] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
```
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                     NUMBER  GLOSS
----------------  ---------  -------------------  --------  ------------------------------------------------
                          7  Klamer-2018-607-6           6  2sg (polite)
                         57  Klamer-2018-607-58         58  burden stick
                         63  Klamer-2018-607-64         64  ground for ritual activities and public meetings
                         82  Klamer-2018-607-83         83  coconut shell
                         90  Klamer-2018-607-91         91  (coral) reef
                         95  Klamer-2018-607-96         96  cross-cousin
                         96  Klamer-2018-607-97         97  cuscus
                        147  Klamer-2018-607-147       147  finished
                        177  Klamer-2018-607-177       177  gebang palm
                        190  Klamer-2018-607-189       189  gum tree; eucalyptus
                        214  Klamer-2018-607-213       213  initiation ceremony
                        243  Klamer-2018-607-242       242  louse (clothing); body louse
                        291  Klamer-2018-607-290       290  old; worn (house)
                        304  Klamer-2018-607-303       303  penalty
                        313  Klamer-2018-607-312       312  rack (for storing food)
                        316  Klamer-2018-607-315       315  raised platform
                        321  Klamer-2018-607-320       320  rice ear bug
                        322  Klamer-2018-607-321       321  rice field
                        323  Klamer-2018-607-322       322  rice grain head
                        330  Klamer-2018-607-329       329  mound of stones for ritual activities
                        352  Klamer-2018-607-351       351  sermon
                        409  Klamer-2018-607-408       408  thatch; reed or grass used for making roofs
                        440  Klamer-2018-607-439       439  chase; run after
                        482  Klamer-2018-607-481       481  hit (drum)
                        494  Klamer-2018-607-493       493  to plant (rice)
                        495  Klamer-2018-607-494       494  to plant (yam)
                        510  Klamer-2018-607-509       509  search for; to hunt for
                        515  Klamer-2018-607-514       514  to chase away, to expel
                        520  Klamer-2018-607-519       519  skewer
                        558  Klamer-2018-607-557       557  traditional house
                        559  Klamer-2018-607-558       558  treaty
                        606  Klamer-2018-607-605       605  young (people)
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
Check: valid_concepticon_id
OK
```
...

### CODE REVIEW

**Comment by LinguList** [comment]
This one fixes #1121

**Comment by LinguList** [comment]
@chrzyki, could I ask you to have a quick look at this list?

**Comment by LinguList** [comment]
I leave it also to you do decide if we need reviewers here.

**Review by chrzyki — APPROVED** [review]
Looks all good, thanks for preparing this! No additional reviews needed I'd say.

**Pull request merged**
