### PR TITLE
Added new concept sets from West Old Turkic to the master list

### PR DESCRIPTION
**Pull request by martino-vic**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [x] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
May need some help with `concepticon notlinked --gloss "NEW_GLOSS"`
...

### CODE REVIEW

**Comment by LinguList** [comment]
Thanks for the PR. I am sorry to only answer now, as I did not see it before. These kinds of PRs with numerous new concepts must normally come with a new concept list, and we usually do not allow too many concepts that are new to be added at once. So we need to find a use-basis for them in at least two or three conceept lists,and from eye-balling the ones you provide, I do not see them. So our procedure would rather be:

1. leave concepts unmapped
2. check sporadically, if they are central for you, if the occur in other lists
3. propose some new concepts (< 20) in a github issue and discuss with concepticon editors

**Comment by LinguList** [comment]
That means, we'd close this PR and ask you to leave the corresponding entries unmapped. You can still add the definitions ina dictionary or in a specific gloss field different from Concepticon, but we cannot handle to add too many concepticon conceepts at once. This would break our workflow and also make it difficult to avoid concept duplicates, if we grow too fast at once.

**Comment by LinguList** [comment]
I am sorry if it happened that you asked me about this and I gave an answer that did not warn you, as I understand it is a lot of work to make all these definitions. They are not lost, if you store them, we could even think of storing definitions in a pool-file that we then check if we encounter so far unmapped concepts that we see multiple times?

**Comment by martino-vic** [comment]
No worries

The idea with the pool-file sounds good! Does it already exist somewhere, or should it rather be launched from scratch?

I'll open a new issue for the < 20 concepts now

**Pull request closed without merging**
