### PR TITLE
Add ITCH (CAUSE ITCHING OR FEEL ITCHY) and remap 'itch' glosses

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [x] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
#1018. I added the concept set ITCH (CAUSE ITCHING OR FEEL ITCHY) (in the broadest sense of the verb) and remapped the lists with 'itch' glosses.
The only thing I missed while preparing a preliminary table of ambiguous glosses in #1018 is Sun-1991-1004-900: 痒 [chinese]; itch [english]. I could not disambiguate the meaning so I left it mapped to ITCH.

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
@AnnikaTjuka would you have time to moderate this?

**Comment by AnnikaTjuka** [comment]
Sure! Based on our discussion in #1018: @LinguList Would you mind taking a look at the remappings?

**Review by LinguList — APPROVED** [review]

**Review by AnnikaTjuka — APPROVED** [review]
Thanks, @Kristina-Pianykh! I would leave the Sun-1991-1004-900 mapping as is if we can't disambiguate it.

**Comment by LinguList** [comment]
All Chinese concepts could in fact be added to a NEW concept set, that would be `ITCH OR ITCHING`, and the definition would hint that this can either be the process that causes itching or the result of that process, both verbal and nominal. 

In the section in Sun, the concepts selected in this chapter are all adjectives or adjective like, but they have these typical adjective-noun transitions, comprising concepts such as "hungry", "thirsty", etc. So I reckon the intended concept that they want to annotate here is indeed "itchy", the adjectival meaning, and I'd even say for this reason one should replace the PAIN mapping with "PAINFUL", since 痛 901 can also have an adjectival or a verbal reading.

**Comment by Kristina-Pianykh** [comment]
The problem with the Chinese concepts is that, judging by the English translations, they can refer not only to the action of the result of itching but also to the property (i.e. 'itchy'). See the following examples:

| ID      | GLOSS           | 
| ------------- |:-------------:|
|Lama-2012-301-279 | 痒 [chinese]; Itchy [english]
|Castro-2010-540-463 | 痒 [chinese]; itchy [english]
|SatterthwaitePhillips-2011-423-188 | 痒 [chinese]; itchy [english]
|Wang-2015-62-53 | 痒 [chinese]; itchy [english]

Although formally, it is still one and the same Chinese word.

**Comment by LinguList** [comment]
Yes, this is typical for Chinese, that the boundaries between word classes are not that sharp. But you have compounds like "scratch itch" that show that the "itch" is rather to be read as a noun. One could expand the category by saying "ITCH OR ITCHY OR ITCHING", which would then include all kinds of itch.

**Comment by Kristina-Pianykh** [comment]
Alright, then I'll add the new concept set ITCH OR ITCHY OR ITCHING to reflect the ambiguity of the Chinese concepts in this case.

**Comment by LinguList** [comment]
Yes, and adding relations to the three ITCHes would also be useful 
(sorry that we didn't decide to do this earlier....)

**Review by LinguList — APPROVED** [review]
Thanks a lot!

**Pull request merged**
