### PR TITLE
Add Goddard-2011-63

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
# Pull request checklist

- [X] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

This PR is based on #142. Note that the explanations are often composed of the semantic primes given in the list. If a semantic prime consists of two words with "~", I based the mapping on the explanation.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@chrzyki Would you mind adding the PDF: [Goddard2011.pdf](https://github.com/concepticon/concepticon-data/files/4791956/Goddard2011.pdf)

**Comment by AnnikaTjuka** [comment]
Output of `concepticon check`:
```
/Users/tjuka/GitHub/Repos/concepticon-data/concepticondata/conceptlists/Goddard-2011-63.tsv
Check: unique_concepticon_gloss
CONCEPTICON_ID      LINE_NO  ID                    NUMBER  GLOSS
----------------  ---------  ------------------  --------  --------------------
                         38  Goddard-2011-63-37        37  be (specificational)
                         41  Goddard-2011-63-40        40  be (locational)
                         50  Goddard-2011-63-49        49  like~way
                         51  Goddard-2011-63-50        50  maybe
                         55  Goddard-2011-63-54        54  for some time
                         58  Goddard-2011-63-57        57  moment
                         64  Goddard-2011-63-63        63  on one side
Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK
```

**Comment by AnnikaTjuka** [comment]
@LinguList Do you have time to moderate this PR? 

I tried to specify the separator in the EXPLANATION column with:
```
{
    "name": "segments",
    "separator": ", ",
    "datatype": "base": "string"
}
```
See: https://github.com/cldf/cldf/blob/master/faq.md

But the explanations also include other datatypes like brackets, dots, and apostrophes. Therefore, I simply used `"datatype": "string"`.

**Comment by LinguList** [comment]
Okay, I'd say, unless somebody volunteers to double check, this is fine as is, as said, for the size of the list. Furthermore, we can either leave it open until the PDF is added, or we can merge now, and add an issue to add the PDF later.

**Comment by AnnikaTjuka** [comment]
Thanks! 
I also checked with the Goddard-2001-42 list and the mappings of the overlapping concepts matched. 

I'll merge this PR and send @chrzyki a mail with the PDF next week (adding the PDF is not very urgent).

**Pull request merged**
