### PR TITLE
Ritchie UniNum update

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
Added the missing numeral and updated the meta data

### CODE REVIEW

**Comment by chrzyki** [comment]
https://github.com/concepticon/concepticon-data/blob/409fce23d9078fceec4fa896672cb250dd3a29aa/concepticondata/conceptlists/Ritchie-2019-111.tsv-metadata.json `"url"` needs to be updated.

**Comment by chrzyki** [comment]
I think since this list was just added we can circumvent adding everything to `retired.json`? @xrotwang @LinguList ?

**Comment by xrotwang** [comment]
Yes, if it wasn't released yet, that's fine.

Christoph Rzymski <notifications@github.com> schrieb am Fr., 25. Okt. 2019,
14:46:

**Comment by chrzyki** [comment]
And it seems as if `concepticon test` doesn't test the `url` metadata?

**Comment by xrotwang** [comment]
Otherwise, `conception rename` would have been the right tool.

Robert Forkel <xrotwang@googlemail.com> schrieb am Fr., 25. Okt. 2019,
14:48:

**Pull request merged**
