### PR TITLE
Add Sims-2020-253

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [x] add new concept list
- [ ] add new metadata
- [x] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
Relates to #813. The source can be found [here](https://evols.library.manoa.hawaii.edu/bitstream/10524/52460/02Sims2020_131_reconsidering.pdf). Please, note that this is not the type of a list we usually deal with with all source glosses having their own entry. As far as I understood, originally, this is a list of cognates where the items in certain languages may slightly differ in meaning or just have a different gloss (e.g., taken from word dictionaries).

For example:
#### Items from languages A, B, C, D (‘snap (v.i.)’)

Snap (v.i.) relates to the entry 'break (of rope)' so I mapped it accordingly.

In other cases, where the ontological category of a concept is not specified, I turned to the sources that the data were taken from and mapped the concepts if I could find whether it's a substantive or a verb.

The reason why some mappings are used twice or more in this list is, again, becausesome lexical items were incorporated together with their original English glosses (see 'left', 'left (hand)', 'left-side')

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
I hope you it's okay if I ask you @LinguList to moderate this PR since you are familiar with this list.

**Comment by Kristina-Pianykh** [comment]
I'm so sorry, I completely forgot about the holiday!
Concerning the `concepticon check`, you can find the output below. I just had a look at it but didn't find anything apart from the things I'm already aware of.


INFO    concepticon/concepticon-data at .
concepticondata\conceptlists\Sims-2020-253.tsv
Check: unique_concepticon_gloss
|CONCEPTICON_ID|LINE_NO|ID|NUMBER|GLOSS|
|---|---|----|-----|----|
|---|26|  Sims-2020-253-25  |       25 | cave (mountain)|
|---|31 | Sims-2020-253-30  |       30 | clear, clean|
|---|32|  Sims-2020-253-31   |      31 | clear/clean|
|---|39 | Sims-2020-253-38  |       38 | dance, jump|
|---|55 | Sims-2020-253-54 |        54 | enclose|
|---|56 | Sims-2020-253-55  |       55 | enclose (sheep)|
|---|59 | Sims-2020-253-58    |     58 | fat (of humans)|
|---|60 | Sims-2020-253-59     |    59 | fear|
|---|61 | Sims-2020-253-60  |       60 | fear difficulty|
|---|62 | Sims-2020-253-61   |      61 | fear, dread|
|---| 65 | Sims-2020-253-64   |      64  |feed, raise|
|---|66 | Sims-2020-253-65   |      65 | fight/go to war|
|---|82  |Sims-2020-253-81   |      81 | grind, pestle|
|---|99 | Sims-2020-253-98   |      98  |hold closely|
|---|103 | Sims-2020-253-102     |  102  lamb, kid|
|---|108 | Sims-2020-253-107     |  107 | learn, teach|
|---|109 | Sims-2020-253-108  |     108 | learn/teach|
|---|114  |Sims-2020-253-113   |    113 | lifespan|
|---|117|  Sims-2020-253-116   |    116|  lock|
|---|118 | Sims-2020-253-117   |    117 | lower seat (not honored)|
|---|126  |Sims-2020-253-125   |    125  |name|
|---|132 | Sims-2020-253-131    |   131  |nod off|
|---|139 | Sims-2020-253-138  |     138 | overflow|
|---|141 | Sims-2020-253-140    |   140 | pant leg|
|---|143 | Sims-2020-253-142    |   142|  patch (n)|
|---|144 | Sims-2020-253-143     |  143 | patch (n.)|
|---|150 | Sims-2020-253-149  |     149  |pit, stone; bullet|
|---|161 | Sims-2020-253-160   |    160|  red, unripe, green, blue|
|---|164 | Sims-2020-253-163   |    163 | return, transport|
|---|170 | Sims-2020-253-169     |  169 | separate, sever|
|---|190 | Sims-2020-253-189   |    189 | snivel|
|---|193 | Sims-2020-253-192   |    192 | snow, hail (v.)|
|---|195  |Sims-2020-253-194   |    194  |solid, durable|
|---|198  |Sims-2020-253-197    |   197|  spew|
|---| 203 | Sims-2020-253-202     |  202  |stand up, rise, jump|
|---|209 | Sims-2020-253-208    |   208 | straight, erect|
|---|219 | Sims-2020-253-218   |    218|  thick, sticky|
|---| 221 | Sims-2020-253-220     |  220|  throw, abandon|
|---|223  |Sims-2020-253-222  |     222 | to exist|
|---|229 | Sims-2020-253-228   |    228  |trip hammer for hulling rice|
|---|231 | Sims-2020-253-230    |   230 | uphold, stretch|
|---| 236  |Sims-2020-253-235    |   235|  vast, wide, extensive|
|---|239 | Sims-2020-253-238     |  238|  warm self by fire|
|---|244 | Sims-2020-253-243 |      243  |weigh (food)|
|---|245  |Sims-2020-253-244     |  244 | weigh (grain)|
|---| 246 | Sims-2020-253-245   |    245  |weight (grain)|
|---|251 | Sims-2020-253-250   |    250 | wound, scar|
|1226 |                   136 | Sims-2020-253-135  |     135  |one year|
|1226        |            254 | Sims-2020-253-253   |    253 | year|
|1501         |            48  |Sims-2020-253-47       |  47  |drill (v.)|
|1501          |           50  |Sims-2020-253-49       |  49  |drill, bore|
|2075           |          90  |Sims-2020-253-89       |  89  |hatch/brood|
|2075           |         184  |Sims-2020-253-183    |   183 | sit on/hatch (egg)|
|244             |        110  |Sims-2020-253-109     |  109  |left|
|244             |        111  |Sims-2020-253-110     |  110  |left (hand)|
|244             |        112  |Sims-2020-253-111     |  111  |left-side|
|302             |        147  |Sims-2020-253-146     |  146 | people, clan|
|302             |        148  |Sims-2020-253-147     |  147  |people; clan|
|3631           |         154  |Sims-2020-253-153    |   153  |pretend|
|3631           |         155  |Sims-2020-253-154     |  154  |pretend, feign|
|3703           |         205  |Sims-2020-253-204     |  204  |sticky|
|3703           |         206  |Sims-2020-253-205     |  205  |sticky, glutinous|
|460             |         18  |Sims-2020-253-17        | 17  |break (v.i., of rope)|
|460             |        189  |Sims-2020-253-188     |  188 | snap (v.i.)|
|581             |        162  |Sims-2020-253-161     |  161  |return|
|581             |        163  |Sims-2020-253-162      | 162  |return to a place|
|609             |         84  |Sims-2020-253-83        | 83 | hail (lit. snow-hail + round)|
|609             |         85  |Sims-2020-253-84        | 84  |hail (n.)|

Check: unique_id
OK
Check: unique_number
OK
Check: matching_concepticon_gloss_and_id
OK
Check: valid_concepticon_gloss
OK

**Comment by LinguList** [comment]
Okay, I have the following suggestions:

Gloss | Concepticon-ID | Concepticon-Gloss
--- | --- | ---
dance, jump | 1879 | DANCE
fear | 781 | FEAR (FRIGHT)
feed | 739 | FEED
learn, teach | 504 | LEARN
lamb, kid | 820 | LAMB

In case of dance, jump, this is a frequent colexification, but I find it fine to link it to dance, without making meta-concepts here. Same to learn, teach, again, usually, in order to make "teach" out of learn, you will use some causative in these languages, and lamb, kid, is primarily referring to the lamb, and a kid is a young animal.

**Comment by LinguList** [comment]
And no worries. Since there were no demonstrations yesterday, it was almost the same as if there was no 1st of May.

**Comment by Kristina-Pianykh** [comment]
Thank you for your suggestions! As far as I can see, 'feed' is already mapped to FEED but there is another entry 'feed, raise' that is left unmapped. The thing with 'fear' is that I could not find if it's a verb or a noun and for this reason I eas hesitant to map it.

**Pull request merged**
