### PR TITLE
Map left-over emotive concepts to the new concept sets

### PR DESCRIPTION
**Pull request by Kristina-Pianykh**
# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
Related to #1014. There are a couple of other lists with the same word forms but I did not map them either because they have a slightly different meaning (e.g., _confusion_ not in the sense of a feeling but rather as a situation) or because I could not disambiguate their exact meaning.

### CODE REVIEW

**Comment by Kristina-Pianykh** [comment]
Annika, would you have some time to moderate this PR? @AnnikaTjuka

**Comment by AnnikaTjuka** [comment]
Sure, I think we need only one reviewer for this. @CarolinHu Would you take a look at the refined mappings?

**Review by CarolinHu — APPROVED** [review]
Sure. Seems all good to me!

**Review by AnnikaTjuka — APPROVED** [review]

**Comment by AnnikaTjuka** [comment]
Great, thanks! @Kristina-Pianykh feel free to merge!

**Pull request merged**
